### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#1018]
In my next few permutations of I/O, to get nodes/faces/edges working, I would like to permanently deprecate/remove our older HDF5 output formats. Removing them will significantly simplify planned changes and also net negative code changes are desirable.

As such, now might be a good time for a release, right before I make that change. Any objections? Also I forget---are we still on lexical versioning or did we switch to dates?

**Comment by pgrete** [comment]
No objection from my side. I don't think I have any data with the old format.

Regarding the release, the current state is that we're on calendar based version targeting a release every 6 month'ish (so next one on May'ish).
I'm also happy to make a release now and announce in that release that the old format is going to be deprecated.
We could also discuss this on Thursday.

**Comment by lroberts36** [comment]
This sounds good to me. One thing to note is that as we move towards more generic forests we are going to have to change the output a little bit (since the meaning of `LogicalLocation`s are going to change a bit).

**Comment by Yurlungur** [comment]
@pgrete that sounds good to me. I'm in favor of making a release nowish and announcing the deprecation.

@lroberts36 we should maybe coordinate since I'm messing with the I/O anyway.

**Comment by Yurlungur** [comment]
Ping @pgrete is there anything we need to merge in before doing a release now?

**Comment by pgrete** [comment]
I just took care of it as discussed last week.
