### ISSUE TITLE
New outputs don't compile without MPI

### ISSUE THREAD

**Issue by c-prather** [parthenon-hpc-lab/parthenon#1030]
Current parthenon `develop` won't compile with the `PARTHENON_DISABLE_MPI` option.  It errors with:
```
parthenon/src/outputs/outputs.cpp:417:15: error: ‘MPI_COMM_WORLD’ was not declared in this scope
  417 |   MPI_Barrier(MPI_COMM_WORLD);
```

`outputs.cpp` just needs a couple `#ifdef` guards, should be a simple fix but likely easier for someone working on that code at the moment.

**Comment by Yurlungur** [comment]
This might be resolved by #1027 actually.

**Comment by pgrete** [comment]
I should be able to finish that PR tomorrow and will double check that this issue here is also fixed along the way.

**Comment by pgrete** [comment]
I compiled #1027 with MPI and without (and with HDF5 and without) and it worked. So the issue seems to be fixed there (on my machine).

**Comment by pgrete** [comment]
Wait. I just realized I never touched that file so I double checked `develop`.
There's no MPI call in `outputs.cpp`.
@bprather can you double check where the error is raised?
