### ISSUE TITLE
Bump Kokkos to 4.4

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#1165]
Kokkos 4.4 has recently been release (changelog herehttps://github.com/kokkos/kokkos/blob/develop/CHANGELOG.md)
There are some relevant additions that we might want sooner than later (e..g, support for the Grace architecture and MI300 uniform memory).
I also looked at the Changelog wrt our current version (4.01) and didn't immediately spot anything that might break in an obvious way.

Are there any reasons/machines/software stacks that prevent a bump to the latest Kokkos version following the upcoming Parthenon release.

ping @Yurlungur @lroberts36 @brryan @bprather @pdmullen

**Comment by Yurlungur** [comment]
On the LANL side I think we want the new features sooner than later too. To build on Venado/Grace-Hopper we want the grace support.

**Comment by pgrete** [comment]
This got directly merged by accident... my bad (but issue solved).
