### ISSUE TITLE
Please remove NO_DEFAULT_PATH from 'find_package(Ascent REQUIRED NO_DEFAULT_PATH)'

### ISSUE THREAD

**Issue by yurivict** [parthenon-hpc-lab/parthenon#1169]
[here](https://github.com/parthenon-hpc-lab/parthenon/blob/develop/CMakeLists.txt#L370)

It prevents cmake from finding the ascent package installed into a standard location.

**Comment by pgrete** [comment]
We've been following the Ascent recommendation, see https://ascent.readthedocs.io/en/latest/QuickStart.html#using-ascent-in-your-project

Also, I'm not even sure there's a "standard" location per se as I'm not aware of any system were Ascent is installed under a, say, `/usr` path.

Does this cause any issue on your end? Maybe we can fix those in a different way.

**Comment by yurivict** [comment]
> Also, I'm not even sure there's a "standard" location per se as I'm not aware of any system were Ascent is installed under a, say, /usr path.

The standard location is /usr/local/lib/cmake (among several others).
The [find_package documentation](https://cmake.org/cmake/help/latest/command/find_package.html) describes the search algorithm.

> Does this cause any issue on your end? Maybe we can fix those in a different way.

Yes, the Ascent package isn't found when NO_DEFAULT_PATH is present.

**Comment by Yurlungur** [comment]
It is very likely that the ascent developers recommend `NO_DEFAULT_PATH` to *avoid* using system libraries, which are likely not what ascent was linked against on supercomputing systems. This is exactly the opposite use-case for, e.g., OpenBSD. @pgrete I recomend we add a build option such as `PARTHENON_USE_SYSTEM_PACKAGES` which switches `NO_DEFAULT_PATH` off.

**Comment by pgrete** [comment]
Yes, that sounds like a good path forward.
I'm happy to add those changes once I'm back.
Otherwise, if @yurivict you'd like to take a stab at it, you're very welcome to.

**Comment by pgrete** [comment]
Now that I wrote it: From the point of packaging is there any issue with setting `-DAscent_DIR=/usr` or wherever Ascent is installed to by default?
Maybe that already fixes this issue (as some var would need to be set anyway).

**Comment by yurivict** [comment]
> Maybe that already fixes this issue (as some var would need to be set anyway).

No vars need to be set by default. find_package should just find the package in the standard location.

**Comment by Yurlungur** [comment]
I just went ahead and submitted an MR. #1171.

**Comment by Yurlungur** [comment]
@yurivict with this change you should be able to just set `-DPARTHENON_USE_SYSTEM_PACKAGES=ON` to automatically import Kokkos and use default system paths for Ascent.
