### ISSUE TITLE
MPI test infrastructure

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#257]
While trying to get the mpi tests running on Summit I noticed that the current testing environment is having a hard time with using non standard wrappers (e.g., `jsrun` on Summit or `ibrun` on TACC's longhorn).
While the test framework in principle allows for passing additional required arguments (such as `--smpiargs="-gpu"` or `-g 4`) it's currently not handled by the default setup.
Thus, we need a more flexible setup to adapt to different environments.

**Comment by JoshuaSBrown** [comment]
Do you have the output for the command that was attempted but failed?

**Comment by pgrete** [comment]
It's less about the command that fails, but the overall infrastructure.
For example, on Summit the batch nodes also have GPUs so the code actually runs even though it is not executed on a compute node, see https://github.com/lanl/parthenon/blob/develop/docs/building.md#cuda-with-mpi

So the "funny" part is in order to run the serial tests on Summit you need to run ctest with `jsrun` so that the serial tests are run on the compute nodes whereas if you want to run MPI test you would not use jsrun to launch ctest but have ctest/python use jsrun to launch the test (not sure jsrun within jsrun is supported/intended).

**Comment by AndrewGaspar** [comment]
My workflow on Sierra has been to do an interactive allocation first and then run ctest in the interactive allocation. That _seems_ to work with `mpiexec`. Have you tried `mpiexec` within `jsrun ctest`?

**Comment by pgrete** [comment]
I have not tried to run with anything other than `jsrun`.
In general, I try to only use the officially supported/recommended launch command as I've been burned in the past by not doing it (e.g., some environment variables were missing or thread/process pinning resulting in hard to reproduce and/or undesired behaviour with respect to performance [or picking the right GPU on a multi GPU system etc.])
