### ISSUE TITLE
Test correct build/export of parthenon as a library

### ISSUE THREAD

**Issue by JoshuaSBrown** [parthenon-hpc-lab/parthenon#273]
Following @junghans comments, the examples can be used as a test. This is in reference to [238](https://github.com/lanl/parthenon/pull/238). This is to ensure that parthenon can be used as a third party library and that it's dependencies are correctly configured. 

Add an `examples` folder with the pi example and a `CMakeLists.txt` like:
```cmake
cmake_minimum_required(VERSION 3.11)
project(parthenon_linking_example)
if(NOT TARGET Parthenon::parthenon)
  find_package(parthenon REQUIRED)
endif()
add_executable(
  pi-example
  pi_driver.cpp
  pi_driver.hpp
  calculate_pi.cpp
  calculate_pi.hpp
  )
target_link_libraries(pi-example PRIVATE Parthenon::parthenon)
```
This `CMakeLists.txt` will work for internal as well as external builds, so you can build that example as part of parthenon, but also standalone. The latter you can add to the CI, so that the exports are always tested.

**Comment by AndrewGaspar** [comment]
Something I've done in another project is to make it so that you can test both paths in the same example project. Something like:

```cmake
option(PARTHENON_EXAMPLE_FIND_PARTHENON "ON for find_package(parthenon), OFF for add_subdirectory(.. parthenon" OFF)

if (PARTHENON_EXAMPLE_FIND_PARTHENON)
    find_package(parthenon REQUIRED)
else()
    add_subdirectory(.. parthenon)
endif()
```

We should also add a library alias for parthenon so that the interface looks the same for the subdirectory case and the library case:
```cmake
add_library(Parthenon::parthenon ALIAS parthenon)
```

**Comment by JoshuaSBrown** [comment]
> Something I've done in another project is to make it so that you can test both paths in the same example project. Something like:
> 
> ```cmake
> option(PARTHENON_EXAMPLE_FIND_PARTHENON "ON for find_package(parthenon), OFF for add_subdirectory(.. parthenon" OFF)
> 
> if (PARTHENON_EXAMPLE_FIND_PARTHENON)
>     find_package(parthenon REQUIRED)
> else()
>     add_subdirectory(.. parthenon)
> endif()
> ```
> 
> We should also add a library alias for parthenon so that the interface looks the same for the subdirectory case and the library case:
> 
> ```cmake
> add_library(Parthenon::parthenon ALIAS parthenon)
> ```

I don't understand, how would this fit in our current configuration setup? Won't the parthenon target already be defined?

**Comment by AndrewGaspar** [comment]
You'd have to configure the examples as the top level directory. You can do something like this to determine if the example is being included as a subdirectory and avoid this whole path. Something like:
```cmake
if (CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    # Get Parthenon if this is the top level directory

    option(PARTHENON_EXAMPLE_FIND_PARTHENON "ON for find_package(parthenon), OFF for add_subdirectory(.. parthenon" OFF)

    if (PARTHENON_EXAMPLE_FIND_PARTHENON)
        find_package(parthenon REQUIRED)
    else()
        add_subdirectory(.. parthenon)
    endif()
endif()

target_link_libraries(advection-example Parthenon::parthenon)
```

So then you can still build examples as part of the normal top-level CMake configuration, but then also use them to test including Parthenon as a subdirectory or as an external package. Of course, then you also need to take defensive measures to not recursively include the examples from the top level parthenon directory. But we should do that, anyway, because we shouldn't be defining the examples by default for people using parthenon as a subdirectory.

**Comment by JoshuaSBrown** [comment]
If this is in the top level directory it makes more sense, but shouldn't this

```
add_subdirectory(.. parthenon)
```

be

```
add_subdirectory(src)
```

Sorry, I'm still a little confused.

**Comment by junghans** [comment]
In my example, I had
```
if(NOT TARGET Parthenon::parthenon)
  find_package(parthenon REQUIRED)
endif()
```
which is basically doing the same as @AndrewGaspar suggested, if the target is already there (meaning we are building the example as a part of the bigger project) do nothing, else find the parthenon (meaning create the target).

**Comment by AndrewGaspar** [comment]
Yeah, that should work, too. Keep in mind you need to make sure the examples are included after the source directory in this case, but that shouldn't be too big of a deal.

**Comment by AndrewGaspar** [comment]
We talked on the phone, and I think I cleared up the confusion about what I'm asking for.

**Comment by JoshuaSBrown** [comment]
Would we want to run these examples, or would it be enough to simply compile them? Running them as tests will take a bit more configuration because of the test infrastructure involved.

**Comment by AndrewGaspar** [comment]
I think it's fine to just build them.

**Comment by Yurlungur** [comment]
Deferred given library vs in-tree build discussion #747
