### ISSUE TITLE
Provide hints for `find_package`?

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#275]
Today I discovered the nasty "feature" that `Anaconda Python` installs its own version of `hdf5` serial. So when I tried to compile `parthenon` regression tests with `hdf5` and `openmpi` and `python`, `cmake` slurped up my anaconda hdf5 instead of my system hdf5. 

My eventual solution for this was to remove anaconda from my path and give `cmake` a hint for where python lives:
```bash
 cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DISABLE_MPI=On -DPython3_ROOT_DIR=${HOME}/anaconda3/ ..
```
Is there a better way? And is there a way we can change our build system to make this less painful?

Pinging the `cmake` gurus @AndrewGaspar and @JoshuaSBrown

**Comment by Yurlungur** [comment]
@brryan suggested that perhaps `find_package` is unsafe and can be made safer?

**Comment by brryan** [comment]
My understanding is something like going from
```cmake
find_package(HDF5 COMPONENTS C)
```
to
```cmake
if(DEFINED PARTHENON_HDF5_PATH)
  find_package(HDF5 COMPONENTS C PATHS ${PARTHENON_HDF5_PATH} NO_DEFAULT_PATH)
else()
  find_package(HDF5 COMPONENTS C)
endif()
```
would give the person compiling parthenon greater precision in providing their dependencies

**Comment by JoshuaSBrown** [comment]
Ya, I think you are hitting on some of the annoying features of cmakes find_package command. This is something I like about spack, if it detects more than one matching package it will print them to the screen. Maybe we could do something similar. The other idea would be to check through all the available python packages and pick the one that satisfies the most requirements.

**Comment by brryan** [comment]
@JoshuaSBrown I like the idea of being more verbose about what libraries are found/chosen. Is this possible in a `find_package` context, though? My understanding is that that call will stop searching as soon as it finds something.

I am still enthusiastic about optional cmake flags that bypass cmake's internal decision engine and just enforce an all-or-nothing approach to user-designated libraries, i.e. use what I requested or throw an error if it's not found. Historically on other projects I have sometimes found it very frustrating to be boxed in by the requirement of accommodating `find_package`'s thought process which has not always been clear to me, and I think others have had a similar experience. 

There are some parallels here to the discussion of machine-specific input files over at #247, I think.

**Comment by AndrewGaspar** [comment]
I think this has been discussed before - CMake has a built-in solution. For any `find_package(Foo ...)`, defining either environment or cmake variable `Foo_ROOT=/path/to/foo/root/dir` takes top priority. See https://cmake.org/cmake/help/latest/command/find_package.html

No reason to define any Parthenon specific variables.

**Comment by AndrewGaspar** [comment]
> I like the idea of being more verbose about what libraries are found/chosen.

When you configure, you should see a printout telling you where CMake found a package. Unfortunately, they don't keep searching, and I don't think find packages are generally architected to support this - they imperatively start defining all sorts of global state, so they don't really have a mode of "please look around for some other HDF5s but don't actually do anything with them".

**Comment by Yurlungur** [comment]
It's worth noting, I think, that going towards machine-specific configuration will help with this some, since the magic combination will be documented by the user in their personal file in their home directory or whatever.

**Comment by pgrete** [comment]
I agree (with the machine files allowing to address this issue transparently), see, e.g., https://github.com/lanl/parthenon/blob/2a2e64e6acfa20ee533f377cfd91037859e2d465/cmake/machinecfg/CI.cmake#L23

**Comment by AndrewGaspar** [comment]
My impression is this issue can be closed - please re-open if you disagree.
