### ISSUE TITLE
An issue with the CI?

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#278]
I've noticed the CI seems to be failing kind of regularly and then passes upon restart. I think this might be coming from the `overlapping space instances` test from `test_kokkos_abstraction`. Do we know what's going on there? Is something going on with the CI server again?

@pgrete @JoshuaSBrown @forrestglines

**Comment by pgrete** [comment]
I think it's a resource with sharing the GPU and having multiple runners.
The overlapping space instances literally assume an ideal environment (e.g., unique allocation of a GPU) so that things actually can overlap.
If there's another test running and using the GPU at the same time, those kernels are also submitted to the same GPU and thus we don't see the overlapping we'd like to have.
Unfortunately, I'm not quite sure how to address this unless reducing the number of concurrent runners to 1, which may increase overall CI time as that machine is also used in other projects.

**Comment by Yurlungur** [comment]
Could we perhaps significantly loosen the bounds on the overlapping space instances test? let it pass unless things are catastrophically slow?

That could be a cmake setting even (though that's probably overkill). It's pretty annoying to have to click "rerun" for every other CI run

**Comment by pgrete** [comment]
I agree. I'm actually wondering if it'd make sense to reorganize the test suite given the current rapid development.
My suggestion is to have a "quick" suite of test that runs in <10 min total and checks basic things (but a complete set) and then run a more complete suite (similar to what we have right now) every night on develop as well as manually triggered before hitting merge for "larger" PRs.

**Comment by Yurlungur** [comment]
> My suggestion is to have a "quick" suite of test that runs in <10 min total and checks basic things (but a complete set) and then run a more complete suite (similar to what we have right now) every night on develop as well as manually triggered before hitting merge for "larger" PRs.

Yes, that sounds like a very good idea to me. 

Perhaps we could just disable performance tests for the "quick" test and only do them on nightly builds?

**Comment by JoshuaSBrown** [comment]
> My suggestion is to have a "quick" suite of test that runs in <10 min total and checks basic things (but a complete set) and then run a more complete suite (similar to what we have right now) every night on develop as well as manually triggered before hitting merge for "larger" PRs.

I'm fine with this, when merging to develop, but we should have nightly test enabled before going in this direction. 

> Unfortunately, I'm not quite sure how to address this unless reducing the number of concurrent runners to 1, which may increase overall CI time as that machine is also used in other projects.

This bears looking into, there should be ways of limiting access to a shared resource so you don't have this problem. Most linux shells will have the ability to lock resources. But yes in the case of only having access to a single gpu this would slow down the ci.

**Comment by Yurlungur** [comment]
> but we should have nightly test enabled before going in this direction.

100% agreed.

**Comment by Yurlungur** [comment]
I've just gone ahead and added a nightly CI run to `develop` . Hope you don't mind me messing with the CI, @pgrete . We can delete it if needed.

I'm also working on a repartition of the tests as I suggested above. My simple, stupid solution is just only do performance and regression tests on the nightly. I'm testing it and will submit a MR soon.
