### ISSUE TITLE
Case insensitive package naming

### ISSUE THREAD

**Issue by brryan** [parthenon-hpc-lab/parthenon#286]
In a similar vein to #264, one can run into surprisingly sneaky errors when variously calling a package name with different capitalizations. Such mistakes can generate relatively obscure compiler errors, e.g. I just lost some time from
```c++
packages["thispackagenameshouldbecapitalized"]->Param<Real>("my_parameter");
```
Similar issues may also be lurking in other places where we use strings to set/get stuff.

**Comment by Yurlungur** [comment]
`[]` no longer allowed with `packages`
