### ISSUE TITLE
All sizes <=1 should be unitialized dimensions

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#295]
In reviewing MR #294 I got very confused by the fact that `IndexShape` uses size=0 to specify unused dimensions, while secretly this is size 1 in the underlying array shape. I think the easiest way to bring these two ideas into alignment is to simply tell `IndexShape` that all sizes <=1 are unused dimensions.

Not a functional change, but it makes things more intuitive for old Athen++ hands.

**Comment by brryan** [comment]
I'm not very familiar with this part of the code but just a quick question: if this change goes in will I still be able to get e.g. the cell width in the j direction if I have a one-zone simulation volume? It would be nice to still have those quantities for particles.

**Comment by Yurlungur** [comment]
The cell width in the `j` direction would be 1. Or do you want 1 zone with ghosts? You might need to do a 2-zone problem for that.

**Comment by brryan** [comment]
Sorry I mean the `Real`-valued physical width, so I can for example distribute particles uniformly in space inside the zone.

**Comment by Yurlungur** [comment]
Oh! Yes, that's still available. The `dx` values are set by `(xmax - xmin)/nx`. So if `nx2=1` the cell witdth is just `x2max-x2min`.

**Comment by brryan** [comment]
OK great, thanks!
