### ISSUE TITLE
Attempt to detect and warn if run launched without cuda aware MPI

### ISSUE THREAD

**Issue by AndrewGaspar** [parthenon-hpc-lab/parthenon#297]
Off the top of my head, I don't remember what the environment variable is, but Spectrum MPI at least sets a specific environment variable to indicate that CUDA aware MPI is enabled. We should check for this when building for CUDA and issue a warning if it's missing. This will help people track down that they're missing the `-gpu` flag faster.

**Comment by Yurlungur** [comment]
Cannot be solved.
