### ISSUE TITLE
Scalability analysis 

### ISSUE THREAD

**Issue by gshipman** [parthenon-hpc-lab/parthenon#301]
A place to discuss scalability

**Comment by gshipman** [comment]
Running on master with @pgrete input deck. We are seeing the following performance on RZAnsel: 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/665019/92631077-1338f880-f28e-11ea-915c-dd25980c697c.png">

Run script: 

```
N=1
NX1=256
NX2=256
NX3=256
echo "N=${N}, NX1=${NX1}, NX2=${NX2}, NX3=${NX3}"
lrun -n ${N} -g 1 -c 10 -M "-gpu" ./example/advection/advection-example -i ./parthinput.advection.weak parthenon/mesh/nx1=${NX1} parthenon/mesh/nx2=${NX2} parthenon/mesh/nx3=${NX3} | tee ${N}.out

N=2
NX1=`expr $NX1 \\* 2 `
echo "N=${N}, NX1=${NX1}, NX2=${NX2}, NX3=${NX3}"
lrun -n ${N} -g 1 -c 10 -M "-gpu" ./example/advection/advection-example -i ./parthinput.advection.weak parthenon/mesh/nx1=${NX1} parthenon/mesh/nx2=${NX2} parthenon/mesh/nx3=${NX3} | tee ${N}.out

 N=4
 NX2=`expr $NX2 \\* 2 `
 echo "N=${N}, NX1=${NX1}, NX2=${NX2}, NX3=${NX3}"
lrun -n ${N} -g 1 -c 10 -M "-gpu" ./example/advection/advection-example -i ./parthinput.advection.weak parthenon/mesh/nx1=${NX1} parthenon/mesh/nx2=${NX2} parthenon/mesh/nx3=${NX3} | tee ${N}.out
```

Input deck: 
```
<parthenon/job>
problem_id = advection

<parthenon/mesh>
refinement = adaptive
numlevel = 2

nx1 = 256
x1min = -0.5
x1max = 0.5
ix1_bc = periodic
ox1_bc = periodic

nx2 = 256
x2min = -0.5
x2max = 0.5
ix2_bc = periodic
ox2_bc = periodic

nx3 = 256
x3min = -0.5
x3max = 0.5
ix3_bc = periodic
ox3_bc = periodic

<parthenon/meshblock>
nx1 = 32
nx2 = 32
nx3 = 32

<parthenon/time>
tlim = 1.0
integrator = rk1
nlim = 10
perf_cycle_offset = 2

<Advection>
cfl = 0.30
vx = 1.0
vy = 1.0
vz = 1.0
profile = smooth_gaussian
ang_2 = 0.0
ang_3 = 0.0
ang_2_vert = false
ang_3_vert = false
amp = 1.0

refine_tol = 1.01    # control the package specific refinement tagging function
derefine_tol = 1.001
compute_error = false
```

**Comment by gshipman** [comment]
GPUs | 3rd cycle | avg of 10 cycles
-- | -- | --
1 | 1.72E+07 | 1.71E+07
2 | 3.35E+07 | 3.32E+07
4 | 6.73E+07 | 6.70E+07
8 | 1.41E+08 | 1.25E+07
16 | 2.79E+08 | 3.04E+07
32 | 5.74E+08 | 5.00E+07
64 | 1.20E+09 | 2.11E+07
128 | 2.40E+09 | 2.39E+09
256 | 4.83E+09 | 4.74E+09
512 | 6.59E+09 | 9.32E+09
1024 | 1.90E+10 | 1.86E+10
2048 | 3.51E+10 | 3.50E+10
4096 | 7.02E+10 | 6.77E+10
8192 | 1.36E+11 | 1.32E+11

<img width="449" alt="image" src="https://user-images.githubusercontent.com/665019/94050787-f6bfb480-fd93-11ea-8455-c0b8a762b0be.png">

**Comment by gshipman** [comment]
<img width="449" alt="image" src="https://user-images.githubusercontent.com/665019/94175916-93498b80-fe54-11ea-8b56-715e969d85eb.png">

**Comment by pgrete** [comment]
![amr-scaling](https://user-images.githubusercontent.com/22685568/96769692-bf1e4980-13df-11eb-8267-56b9aaba077d.png)

**Comment by cielling** [comment]
> GPUs 	3rd cycle 	avg of 10 cycles
> 1 	1.72E+07 	1.71E+07
> 2 	3.35E+07 	3.32E+07
> 4 	6.73E+07 	6.70E+07
> 8 	1.41E+08 	1.25E+07
> 16 	2.79E+08 	3.04E+07
> 32 	5.74E+08 	5.00E+07
> 64 	1.20E+09 	2.11E+07
> 128 	2.40E+09 	2.39E+09
> 256 	4.83E+09 	4.74E+09
> 512 	6.59E+09 	9.32E+09
> 1024 	1.90E+10 	1.86E+10
> 2048 	3.51E+10 	3.50E+10
> 4096 	7.02E+10 	6.77E+10
> 8192 	1.36E+11 	1.32E+11
> 
> <img alt="image" width="449" src="https://user-images.githubusercontent.com/665019/94050787-f6bfb480-fd93-11ea-8455-c0b8a762b0be.png">

This was _not_ done on a single node, correct?

**Comment by cielling** [comment]
Edit: These plots are OUT OF DATE! See here for up to date plots:
[buffer-in-one-tau_summaries.ipynb](https://github.com/lanl/parthenon/blob/cielling/scaling_analysis_ipynbs/weakscaling/buffer-in-one-tau_summaries.ipynb)
[buffer-in-one-weakscaling.ipynb](https://github.com/lanl/parthenon/blob/cielling/scaling_analysis_ipynbs/weakscaling/buffer-in-one-weakscaling.ipynb)
--------

![zonecyclesperwsecplot](https://user-images.githubusercontent.com/4451435/99996927-aa83f700-2d79-11eb-9a83-2dd7f3eda308.png)

This may not be meaningful, but plotting the average of the 'zone-cycles/wsec' for cycles 4-10 gives a somewhat different behavior than plotting the 'zone-cycles/wallsecond' number output at the end of the run (which is cumulative over all cycles that are included in the measurement). Perhaps plotting these numbers per meshblock would be more meaningful.
Also note, for 16 GPUs there is a roughly 2 orders of magnitude variation from cycle to cycle.

For future reference, this is using the `develop` branch commit `f47690fc`.

**Comment by cielling** [comment]
Edit: These plots are OUT OF DATE! See here for up to date plots:
[buffer-in-one-tau_summaries.ipynb](https://github.com/lanl/parthenon/blob/cielling/scaling_analysis_ipynbs/weakscaling/buffer-in-one-tau_summaries.ipynb)
[buffer-in-one-weakscaling.ipynb](https://github.com/lanl/parthenon/blob/cielling/scaling_analysis_ipynbs/weakscaling/buffer-in-one-weakscaling.ipynb)
--------

![Kokkos_totals_linscale](https://user-images.githubusercontent.com/4451435/99997435-634a3600-2d7a-11eb-864f-c32a410469aa.png)
![MPI_totals_linscale](https://user-images.githubusercontent.com/4451435/99997547-8d9bf380-2d7a-11eb-97bb-d0f42f12f918.png)
Same as above, but in log-scale
![MPI_totals_logscale](https://user-images.githubusercontent.com/4451435/100002489-dc00c080-2d81-11eb-9517-60837e3acbd4.png)


Plotting the timings for different functions/Kokkos kernels as reported by tau. The times are the totals for a run, and are inclusive (though there don't appear to be any overlapping timer regions).

**Comment by pgrete** [comment]
@cielling thanks for sharing the plots. Especially the first one is very interesting.
I'll update my buffer-in-one branch tomorrow and then we should see a dramatic improvement in the packing timings (>30x).
Also the changes #378 may make it easier to get a complete picture of Parthenon. IIRC tau can process the Kokkos profiling regions.

**Comment by cielling** [comment]
Edit: These plots are OUT OF DATE! See here for up to date plots:
[buffer-in-one-tau_summaries.ipynb](https://github.com/lanl/parthenon/blob/cielling/scaling_analysis_ipynbs/weakscaling/buffer-in-one-tau_summaries.ipynb)
[buffer-in-one-weakscaling.ipynb](https://github.com/lanl/parthenon/blob/cielling/scaling_analysis_ipynbs/weakscaling/buffer-in-one-weakscaling.ipynb)
--------
Two more plots from the tau profiling runs, the time per call for Kokkos and MPI calls:

![Kokkos_percall_linscale](https://user-images.githubusercontent.com/4451435/100012698-eb3b3a80-2d90-11eb-8c49-26e1da3b0b4f.png)
![MPI_percall_linscale](https://user-images.githubusercontent.com/4451435/100012714-f1c9b200-2d90-11eb-9c34-56a957ae0279.png)

**Comment by cielling** [comment]
Here are some plots of the profiles I got from Tau for the runs with nGPUs = 4 (1 node), 8 (2 nodes), and 32 (8 nodes). The runs were done with the `pgrete/buffer-in-one` branch (commit de6349d), and I had the environment variables `TAU_TRACE`, `TAU_PROFILE`, `TAU_TRACK_MESSAGE`, and `TAU_COMM_MATRIX` set. 

It does seem that MPI communication is to blame for the drop in scaling at 8 GPUs.

![trace4](https://user-images.githubusercontent.com/4451435/102549642-b2357380-4079-11eb-8dff-528ecfaed835.jpg)
![trace8](https://user-images.githubusercontent.com/4451435/102549658-b8c3eb00-4079-11eb-8761-ffa28cd3b803.jpg)
![trace32](https://user-images.githubusercontent.com/4451435/102549666-be213580-4079-11eb-94af-e3fa30155594.jpg)

**Comment by cielling** [comment]
And here are plots of the communication matrix for those runs that Tau gave me. These ones show the number of calls and the total volume of bytes sent (also available in Tau were mean, std. dev., and max size of the messages sent). I'm not sure how insightful these are as-is.

![comm_matrix](https://user-images.githubusercontent.com/4451435/102550781-a3e85700-407b-11eb-84d0-96dabf00d21c.jpg)

**Comment by cielling** [comment]
More plots here:
[buffer-in-one-tau_summaries.ipynb](https://github.com/lanl/parthenon/blob/cielling/scaling_analysis_ipynbs/weakscaling/buffer-in-one-tau_summaries.ipynb)
[buffer-in-one-weakscaling.ipynb](https://github.com/lanl/parthenon/blob/cielling/scaling_analysis_ipynbs/weakscaling/buffer-in-one-weakscaling.ipynb)

**Comment by pgrete** [comment]
> Here are some plots of the profiles I got from Tau for the runs with nGPUs = 4 (1 node), 8 (2 nodes), and 32 (8 nodes). The runs were done with the `pgrete/buffer-in-one` branch (commit [de6349d](https://github.com/lanl/parthenon/commit/de6349df75e6d5a42a7c31b175f72660a2468f87)), and I had the environment variables `TAU_TRACE`, `TAU_PROFILE`, `TAU_TRACK_MESSAGE`, and `TAU_COMM_MATRIX` set.
> 
> It does seem that MPI communication is to blame for the drop in scaling at 8 GPUs.
> 

Thanks for sharing! This looks very interesting.
I'd be curious to compare the results using the Kokkos tools for the regions for the same configuration.
I'm wondering if the MPI tau results are potentially misleading (in terms of where the time is actually spent) or if there's something unexpected going on in the MPI library.
IIRC MPI_Start is nonblocking and therefore should effectively not show up at all as a significant region.

**Comment by cielling** [comment]
> 
> Thanks for sharing! This looks very interesting.
> I'd be curious to compare the results using the Kokkos tools for the regions for the same configuration.
> I'm wondering if the MPI tau results are potentially misleading (in terms of where the time is actually spent) or if there's something unexpected going on in the MPI library.
> IIRC MPI_Start is nonblocking and therefore should effectively not show up at all as a significant region.

I can look into that.

**Comment by Yurlungur** [comment]
In parthenon paper
