### ISSUE TITLE
Back pointers to meshblocks should be shared pointers.

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#306]
Since MR #303 makes the meshblock list own shared pointers, we can now take advantage of this with our back pointers, as @AndrewGaspar points out.

**Comment by AndrewGaspar** [comment]
They should be weak pointers. If they're shared pointers, that will cause circular shared pointers and you'll leak memory.

**Comment by Yurlungur** [comment]
yes sorry that's what I meant.

**Comment by Yurlungur** [comment]
Upon reflection, this is more challenging than I thought it would be. In particular, the meshblock sets back-pointers to it itself. I.e., 
```C++
auto &real_container = real_containers.Get();
real_container->setBlock(this);
```
I think cleaning up the back pointers is worth doing, but it's not a simple find-replace like I thought. So I'm putting it off for now.

**Comment by AndrewGaspar** [comment]
Yeah, you'd have to derive `MeshBlock` from [`std::enabled_shared_from_this`](https://en.cppreference.com/w/cpp/memory/enable_shared_from_this).

**Comment by Yurlungur** [comment]
> Yeah, you'd have to derive `MeshBlock` from [`std::enabled_shared_from_this`](https://en.cppreference.com/w/cpp/memory/enable_shared_from_this).

Oh that's cool. I wasn't aware of that capability. I'll revisit this in a bit using that.
