### ISSUE TITLE
Bug in mpi restart regression test/infrastructure

### ISSUE THREAD

**Issue by JoshuaSBrown** [parthenon-hpc-lab/parthenon#312]
There is a bug somewhere it is either in parthenon or in the testing infrastructure. I have located it to occurring after calling \_\_import\_\_ in the python test_case file. Any time the mpi restart test is called using subprocess.run(".."), os.system("...") or any other subprocess command it is like the test simply dies and the python script throws an error but I have been unable to get output from the mpi call test call except for the error code. If the subprocess command or the os.system commands are moved infront of the dynamic import command (\_\_import\_\_) the tests will run successfully to their conclusion. The tests also run fine if run in serial. 

I am not quite sure what is causing this, I think either there is something going on with python's dynamic import or there is some serious memory clobbering occuring in parthenon that is causing some corruption when run with mpi. I noticed the problem while looking over @nmsriram's restart fix pull request. https://github.com/lanl/parthenon/pull/311. It is not even clear if this was introduced by the restart functionality or before because the restart regression test was failing when the pull request was merged in. It's possible that there is an error that was already present that the restart functionality simply exposed. 

The test fails no matter if I use a single mpi proc or several. 

I have been building on darwins power9 nodes with the following:

cmake -DCMAKE_CXX_COMPILER=${PWD}/../external/Kokkos/bin/nvcc_wrapper -DCMAKE_CXX_FLAGS="-Xcudafe --diag_suppress=esa_on_defaulted_function_ignored" -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_POWER9=ON -DKokkos_ARCH_VOLTA70=ON -DNUM_MPI_PROC_TESTING=2 ..

  module load cmake/3.12.4                                                                           
  module load gcc/7.4.0                                                                              
  module load clang/8.0.1                                                                            
  module load openmpi/p9/4.0.2-gcc_7.4.0                                                             
  module load cuda/10.1                                                                                                                                                    
  spack load hdf5%gcc@7.4.0                                                                          
  spack load py-h5py                                                                                 
  spack load py-matplotlib    

Output from a failed run:

```
ctest --verbose -R "mpi.*restart"
UpdateCTestConfiguration  from :/home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/DartConfiguration.tcl
Parse Config file:/home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/DartConfiguration.tcl
Parse Config file:/home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/DartConfiguration.tcl
Test project /home/joshuasbrown/Software/parthenon_x86_64/parthenon/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 27
    Start 27: regression_mpi_test:restart

27: Test command: /home/joshuasbrown/Software/spack_env/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/python-3.7.7-yaizuaarl3uabyca7bt463q6rzqdfqe2/bin/python3.7 "/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/run_test.py" "--mpirun" "/projects/opt/ppc64le/p9/openmpi/4.0.2-gcc_7.4.0/bin/mpiexec" "--mpirun_opts=-n" "--mpirun_opts=4" "--mpirun_opts=" "--driver" "/home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/example/advection/advection-example" "--driver_input" "/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/test_suites/restart/parthinput.restart" "--num_steps" "2" "--test_dir" "/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/test_suites/restart" "--output_dir" "/home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/tst/regression/outputs/restart_mpi"
27: Test timeout computed to be: 1500
27: {'test_dir': ['/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/test_suites/restart'], 'output_dir': '/home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/tst/regression/outputs/restart_mpi', 'driver': ['/home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/example/advection/advection-example'], 'driver_input': ['/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/test_suites/restart/parthinput.restart'], 'num_steps': 2, 'mpirun': ['/projects/opt/ppc64le/p9/openmpi/4.0.2-gcc_7.4.0/bin/mpiexec'], 'mpirun_opts': ['-n', '4', ''], 'coverage': False}
27: *****************************************************************
27: Beginning Python regression testing script
27: *****************************************************************
27: Initializing Test Case
27: Using:
27: driver at:       /home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/example/advection/advection-example
27: driver input at: /home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/test_suites/restart/parthinput.restart
27: test folder:     /home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/test_suites/restart
27: output sent to:  /home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/tst/regression/outputs/restart_mpi
27: 
27: --------------------------------------------------------------------------
27: WARNING: There was an error initializing an OpenFabrics device.
27: 
27:   Local host:   cn2025
27:   Local device: mlx5_3
27: --------------------------------------------------------------------------
27: Make output folder in test if does not exist
27: *****************************************************************
27: Preparing Test Case Step 1
27: *****************************************************************
27: *****************************************************************
27: Running Driver
27: *****************************************************************
27: Command to execute driver
27: ['/projects/opt/ppc64le/p9/openmpi/4.0.2-gcc_7.4.0/bin/mpiexec', '-n', '4', '/home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/example/advection/advection-example', '-i', '/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/test_suites/restart/parthinput.restart', 'parthenon/job/problem_id=gold']
27: Traceback (most recent call last):
27:   File "/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/utils/test_case.py", line 231, in Run
27:     proc = subprocess.run(run_command, check=True, stdout=PIPE, stderr=PIPE)
27:   File "/home/joshuasbrown/Software/spack_env/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/python-3.7.7-yaizuaarl3uabyca7bt463q6rzqdfqe2/lib/python3.7/subprocess.py", line 512, in run
27:     output=stdout, stderr=stderr)
27: subprocess.CalledProcessError: Command '['/projects/opt/ppc64le/p9/openmpi/4.0.2-gcc_7.4.0/bin/mpiexec', '-n', '4', '/home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/example/advection/advection-example', '-i', '/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/test_suites/restart/parthinput.restart', 'parthenon/job/problem_id=gold']' returned non-zero exit status 1.
27: 
27: During handling of the above exception, another exception occurred:
27: 
27: Traceback (most recent call last):
27:   File "/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/run_test.py", line 139, in <module>
27:     main(**vars(args))
27:   File "/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/run_test.py", line 68, in main
27:     test_manager.Run()
27:   File "/home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/utils/test_case.py", line 235, in Run
27:     .format(err.returncode, ' '.join(err.cmd)))
27: utils.test_case.TestManagerError: 
27: Return code 1 from command '/projects/opt/ppc64le/p9/openmpi/4.0.2-gcc_7.4.0/bin/mpiexec -n 4 /home/joshuasbrown/Software/parthenon_x86_64/parthenon/build/example/advection/advection-example -i /home/joshuasbrown/Software/parthenon_x86_64/parthenon/tst/regression/test_suites/restart/parthinput.restart parthenon/job/problem_id=gold'
1/1 Test #27: regression_mpi_test:restart ......***Failed    1.48 sec
```

**Comment by AndrewGaspar** [comment]
I repro. Let me take a look.

**Comment by AndrewGaspar** [comment]
So I did a test running `env` from my shell, and then env from test_case.py just before running the test. The green is the new variables - mostly MPI related. I wonder where those are coming from?

![image](https://user-images.githubusercontent.com/2292643/95636718-0c4c0400-0a4d-11eb-8709-08692a2e8ac3.png)

**Comment by AndrewGaspar** [comment]
It's important to note that even things like `mpiexec hostname` don't work, so it's something related to mpi launch.

**Comment by AndrewGaspar** [comment]
Yeah, so I can confirm that the `__import__(self.__test_module` bit is where it starts to fail - prior to that call, mpiexec blah works fine, and then after it fails.

**Comment by AndrewGaspar** [comment]
environment doesn't change around that call, though, so the environment differences may be unrelated.

**Comment by AndrewGaspar** [comment]
Here's an interesting data point - it doesn't fail before running the advection driver if I comment out `import h5py` in restart.py

Obviously it fails later when restart.py tries to use h5py.

**Comment by JoshuaSBrown** [comment]
@AndrewGaspar thanks for taking a look.

**Comment by JoshuaSBrown** [comment]
The mpi regression performance tests also fails. This test started failing after the first restart pr was merged.

**Comment by AndrewGaspar** [comment]
Tracking it into h5py now... starts failing after line 26. down the rabbit hole we go...

![image](https://user-images.githubusercontent.com/2292643/95778384-41429b80-0c85-11eb-9818-561a577e6f8c.png)

**Comment by AndrewGaspar** [comment]
I'm no python export, but I don't see an `_errors.py` file or `_errors/__init__.py` file. I guess I can try stepping until it reaches code?

**Comment by AndrewGaspar** [comment]
oh, it's because it's a native shared library. hrrmmmmmmmmm this is going to make my life hard.

**Comment by Yurlungur** [comment]
If the bug is in h5py, there may not be an easy fix. 

We can perhaps fix this by moving the `h5py` import into just the region needed? I think there's a way to isolate scope and side effects for imports.

We could even call the plotting code in a python subprocess to fully isolate.

**Comment by AndrewGaspar** [comment]
It _appears_ as if loading the `_errors` module causes `MPI_Init` to be called, and that's what is causing this issue. Yeah, maybe if we somehow unloaded `h5py` after we were done with it, that would clean up MPI...

**Comment by AndrewGaspar** [comment]
there's a [`reload`](https://docs.python.org/2.7/library/functions.html#reload) function, but that's not really what I want.

**Comment by AndrewGaspar** [comment]
i'll see if I can try a subprocess.

**Comment by AndrewGaspar** [comment]
I'm not sure how I want to do this that doesn't make the code disgusting. :P

**Comment by Yurlungur** [comment]
My thinking with subprocess was that we could make the plotting script it's own executable, which the test infrastructure calls via `subprocess`.

Alternatively, I don't know if it will fully protect us, but there's [`nose isolate`](https://nose.readthedocs.io/en/latest/plugins/isolate.html)

**Comment by AndrewGaspar** [comment]
This seems to be working for me:

```python
    def Analyse(self, parameters):
        script = """
import h5py
import sys

# spotcheck one variable
goldFile = 'gold.out0.00002.rhdf'
silverFile = 'silver.out0.00002.rhdf'

gold = h5py.File(goldFile,'r')
silver = h5py.File(silverFile,'r')

varName = "/advected"
goldData = gold[varName][:].flatten()
silverData = gold[varName][:].flatten()

# spot check on one variable
maxdiff = max(abs(goldData-silverData))
print('Variable: %s, diff=%g, N=%d'%(varName,maxdiff,len(goldData)))

if maxdiff == 0.0:
    exit = 0
else:
    exit = 1

sys.exit(exit)
"""
        proc = subprocess.run([sys.executable, "-c", script])

        return (proc.returncode == 0)
```

**Comment by AndrewGaspar** [comment]
This is specifically for the restart.py test.

**Comment by Yurlungur** [comment]
Whoof. That's gross. But I think it's a good solution.

**Comment by AndrewGaspar** [comment]
I hate it.
