### ISSUE TITLE
Inner loop pattern tags not portable

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#319]
I recently ran into an issue with `par_for_inner` default loop pattern. The issue is that the `inner_*_tag` variables are global and thus don't have host-device scope so dispatch can fail on lower optimization levels. Essentially, generically this fails:
```cuda
struct S {} s;

__host__ __device__ void bar(S) {
}

__host__ __device__ void foo(){
  bar(s);
}
```
but this succeeds:
```cuda
struct S {};
__device__ S s;

__host__ __device__ void bar(S) {
}

__host__ __device__ void foo(){
  bar(s);
}
```
This also succeeds
```cuda
struct S {};

__host__ __device__ void bar(S) {
}

__host__ __device__ void foo(){
  bar(S());
}
```
as does this
```C++
struct S {};
constexpr S s;

__host__ __device__ void bar(S) {
}

__host__ __device__ void foo(){
  bar(s);
}
```
We currently do the former and we need to change to one of the latter. See the discussion in the Kokkos chat [here](https://kokkosteam.slack.com/archives/C5BGU5NDQ/p1602271717063700)

**Comment by Yurlungur** [comment]
Tagging @pgrete and @forrestglines since they designed the tag system.

**Comment by forrestglines** [comment]
I can see how that would fail and why it compiles fine for higher opt levels. We never address the tag object within the kernel, we just use the type to control which version of the inner loop get compiled.

This looks like it works:
```
struct S {} __device__ s;

__host__ __device__ void bar(S) {
}

__host__ __device__ void foo(){
  bar(s);
}
```

so we could just add `__device__` to the tags and it should compile.

**Comment by Yurlungur** [comment]
The one reason I lean against that solution is that it uses a CUDA, not Kokkos feature and will not be portable. My preferred solution, I think, is to make the tag objects constexpr, which seems to work for me at least in a simple test.

**Comment by forrestglines** [comment]
I agree, `constexpr` would be better.

I can't get this error to appear while compiling with `-O0` with `gcc`. However, if the `constexpr` fix works in the small example, it should work to just add `constexpr` to the two `inner_loop_pattern` structs. It compiles at least in my build.

**Comment by jonahm-LANL** [comment]
Cool. I'll submit a PR then.


---
Dr. Jonah Miller
Scientist
Pronouns: He/Him
Center for Theoretical Astrophysics
Computational Physics and Methods, CCS-2
Los Alamos National Laboratory
Office: 505-665-8387
Cell: 505-551-4274
jonahm@lanl.gov
www.thephysicsmill.com
________________________________

**Comment by Yurlungur** [comment]
It's worth noting that I only encountered this when importing `parthenon` as a submodule of our internal code. I'm not sure why that's the case, but... 🤷
