### ISSUE TITLE
Set-up project space on RZAnsel and add machine config

### ISSUE THREAD

**Issue by AndrewGaspar** [parthenon-hpc-lab/parthenon#348]
TODO: I'm figuring out what the path to the EAP project space is on RZAnsel - stay tuned.

Just start out by putting the project space in your own home directory and we can move it to the project space when we hve it.

Project space setup: https://xcp-gitlab.lanl.gov/eap-oss/parthenon-project

You'll need to:
- [ ] Add new environments in parthenon-project/environments for rzansel
  - probably can copy from darwin/ppc64le as a starting point
- [ ] Add a new RZAnsel.cmake machinecfg
  - There's probably some refactoring to Darwin.cmake that could be done to reuse code
  - make sure `MPI_ROOT` and `CUDAToolkit_ROOT` matches what is used in the parthenon-project spack environment
- [ ] Update `.bashrc` and `.cshrc` in parthenon-project to detect the machine and set MACHINE_CFG appropriately
- [ ] Update parthenon-project/new-view to know about rzansel

**Comment by JoshuaSBrown** [comment]
Sounds good.

**Comment by JoshuaSBrown** [comment]
Is there a specific compiler that we want to go with or is gcc fine?

**Comment by AndrewGaspar** [comment]
OH, use gcc.
