### ISSUE TITLE
Detect absence of `python`

### ISSUE THREAD

**Issue by jlippuner** [parthenon-hpc-lab/parthenon#398]
I have `python2` and `python3` but not `python`, which results in a lot of build errors. We should deal with this. At least warn if there is no `python` and better yet detect what versions are available and choose one that exists.

**Comment by JoshuaSBrown** [comment]
I thought only python3 was supported and that should be called directly. Where are you getting erorrs?

**Comment by JoshuaSBrown** [comment]
The run_test.py script in the regression folder has a shebang specifying python3, all the other test modules are imported from that file so I'm surprised that it would create a problem.

**Comment by pgrete** [comment]
Is this potentially happening in the linting step?
I see that
`tst/style/cpplint.py:#!/usr/bin/env python` tries to directly all call `python`

**Comment by jlippuner** [comment]
Yeah, I think it's at the linting step. We should add a check in CMake to make sure we have `python3` or `python` (and it's version 3 if that's all that's supported) and then adjust `cpplint.py` accordingly.
