### ISSUE TITLE
Detect wrong package name

### ISSUE THREAD

**Issue by jlippuner** [parthenon-hpc-lab/parthenon#399]
I ran into the issue where I changed the name (label) of a package in one place, but not in other places. This resulted in the code just hanging without any error message.

I think we should disallow the use of the `operator[]` for the packages Dictionary, so that we always have to explicitly get a package (using `at()`) or add one (using `insert()`) and we won't have a situation where we want to get a package, but specify the wrong name, and hence actually create an empty package.

**Comment by Yurlungur** [comment]
We could also make `Packages_t` a think wrapper around the dictionary with a bounds-checking `operator[]`.

**Comment by jlippuner** [comment]
This was fixed by #425
