### ISSUE TITLE
Split `pman.ParthenonInit`?

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#409]
@jdolence @Yurlungur (specifically pinging you because of your downstream app):

What do you think about splitting `ParthenonInit` into a) pure initialization of Kokkos/MPI/Cuda and command line parsing and b) initialization of the packages/Mesh/etc?

I'm bringing this up as I was thinking about how to allow runtime configurable problem generator etc.
Currently, 
```
  pman.app_input->ProcessPackages = MyApp::ProcessPackages;
  pman.app_input->InitUserMeshData = my_problem::InitUserMeshData;
  pman.app_input->ProblemGenerator = my_problem::ProblemGenerator;
  pman.app_input->UserWorkAfterLoop = my_problem::UserWorkAfterLoop;
```
need to be set before ParthenonInit as those (or some) functions are called during Init.
If we split  `ParthenonInit` then the `pman->pinput` object would be populated with the current config and the problem generators etc could be customized, e.g., sth along
```c++
  // call ParthenonInit to initialize MPI and Kokkos, parse the input deck, and set up
  auto manager_status = pman.ParthenonInitEnv(argc, argv);
  if (manager_status == ParthenonStatus::InitEnvComplete) {
    pman.ParthenonFinalize();
    return 0;
  }
  if (manager_status == ParthenonStatus::error) {
    pman.ParthenonFinalize();
    return 1;
  }
  // now pinput contains all required configuration for this run and we can customize based on that 
  auto pgen_name = pman.pinput->GetString("job", "pgen");
  if (pgen_name == "prob_a" {
    pman.app_input->InitUserMeshData = my_problem_a::InitUserMeshData;
    pman.app_input->ProblemGenerator = my_problem_a::ProblemGenerator;
    pman.app_input->UserWorkAfterLoop = my_problem_a::UserWorkAfterLoop;  
  else if (pgen_name == "prob_b" {
    pman.app_input->InitUserMeshData = my_problem_b::InitUserMeshData;
    pman.app_input->ProblemGenerator = my_problem_b::ProblemGenerator;
  }
  
  manager_status = pman.ParthenonInitMesh();
  if (manager_status == ParthenonStatus::InitMeshComplete) {
    pman.ParthenonFinalize();
    return 0;
  }
  if (manager_status == ParthenonStatus::error) {
    pman.ParthenonFinalize();
    return 1;
  }
```

**Comment by Yurlungur** [comment]
I think this is a good idea. Actually, @clellsolomon suggested a similar splitting some time ago. We currently select our problem generators with some cmake magic. Changing the parthenon manager to enable selecting at runtime would be a major improvement.

**Comment by jdolence** [comment]
I think I even have a PR... #385 

Something is broken in that that I never tracked down and I'm not sure it does exactly what you want, but it might be a place to start.
