### ISSUE TITLE
Release 0.4

### ISSUE THREAD

**Issue by AndrewGaspar** [parthenon-hpc-lab/parthenon#414]

**Comment by JoshuaSBrown** [comment]
Ya, what do I need to do for this?

**Comment by pgrete** [comment]
If I haven't forgotten anything the key pieces would be
- Open a new PR with
  - the version number updated in `CMakeCache.txt`
  - updated changelog (add version number and date to the "current" heading and create a new "current" heading with the same subheadings as before)
- Merge that PR into develop
- Merge develop into main
- Create a new official release (https://github.com/lanl/parthenon/releases) and copy contents from Changelog

@AndrewGaspar did I miss anything?

**Comment by JoshuaSBrown** [comment]
> If I haven't forgotten anything the key pieces would be
> 
>     * Open a new PR with
>       
>       * the version number updated in `CMakeCache.txt`
>       * updated changelog (add version number and date to the "current" heading and create a new "current" heading with the same subheadings as before)
> 
>     * Merge that PR into develop
> 
>     * Merge develop into main
> 
>     * Create a new official release (https://github.com/lanl/parthenon/releases) and copy contents from Changelog
> 
> 
> @AndrewGaspar did I miss anything?

Thanks @pgrete

**Comment by JoshuaSBrown** [comment]
Should I also create a version tag?

**Comment by AndrewGaspar** [comment]
Yes, after merging.

**Comment by AndrewGaspar** [comment]
When you do the tag, a release will be added to the "Releases" tab automatically. You'll need to update that release with the changelog contents. Conversely, I think when you do a release, it will also create a tag. So whichever way is easiest is fine.
