### ISSUE TITLE
AMR performance 1/N: Single large comm buffers versus 100+ small ones

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#415]
My current interpretation of profiling data on GPU suggests that (especially during load balance and mesh refinement) quite a bit of time is spent in allocating and deallocating comm buffers.
Current each buffer is is a separate Kokkos view, i.e., there are >100 (tiny) buffers for each MeshBlock.
This could be circumvented by using a single buffer with separate offsets.

**Comment by Yurlungur** [comment]
Or kokkos subviews?

**Comment by pgrete** [comment]
Correct, that could also be an option to explore. I think the key piece is to get rid of all the tiny mallocs.

**Comment by Yurlungur** [comment]
I'd argue starting with subviews is the way to go, as it's probably simpler logic. And if it stops being a bottleneck, then we can stop worrying about it, even if it isn't perfect.

**Comment by lroberts36** [comment]
I think this issue maybe should be closed at this point since the buffers because #493 has been merged. #663 also allocates one single large buffer and reuses previous allocations.

**Comment by Yurlungur** [comment]
:+1:
