### ISSUE TITLE
AMR performance 4/N: Reorder buffer routine by "distance"

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#418]
My current interpretation of profiling data on GPU suggests that a significant fraction of a timestep is spent in infrastructure parts (specifically waiting for MPI comm to be done).
Thus, buffer filling could be reordered, so that the current approach (in #359 )
1. Collect data (indices and data pointers) for all buffers
2. Fill all buffers (where buffers for neighboring MeshBlocks on the same rank are directly filled) in single kernel
3. Wait for kernel to be done
4. Start all MPI_Send

is replaced by an approach that takes the distance into account, e.g.,

1. Collect data (indices and data pointers) for for neighboring MeshBlocks on other ranks
2. Fill all buffers for neighboring MeshBlocks on other ranks in single kernel 
3. Wait for kernel to be done
4. MPI_send for those buffer
5. Collect data (indices and data pointers) for for neighboring MeshBlocks on the same rank
6. Fill all buffer for neighboring MeshBlocks on the same rank in single kernel

The latter approach may likely also benefit from using different streams to allow for additional overlap of computation and communication (e.g., step 3 and 4 can overlap with 5 and 6).

**Comment by lroberts36** [comment]
In #663, the option to split the communication tasks into local and non-local channels is implemented. The task list would look something like 
```c++
const auto local = parthenon::BoundaryType::local;
const auto nonlocal = parthenon::BoundaryType::nonlocal;
auto send_nonloc =
    tl.AddTask(update, parthenon::cell_centered_bvars::SendBoundBufs<nonlocal>, mc1);
auto send_loc =
    tl.AddTask(update, parthenon::cell_centered_bvars::SendBoundBufs<local>, mc1);
auto recv_loc =
    tl.AddTask(update, parthenon::cell_centered_bvars::ReceiveBoundBufs<local>, mc1);
auto set_loc = 
    tl.AddTask(recv_loc, parthenon::cell_centered_bvars::SetBounds<local>, mc1);
auto recv_nonloc =
    tl.AddTask(update, parthenon::cell_centered_bvars::ReceiveBoundBufs<nonlocal>, mc1);
auto set_nonloc = 
    tl.AddTask(recv_nonloc, parthenon::cell_centered_bvars::SetBounds<nonlocal>, mc1);
``` 

I tested it for the advection test problems and it gives correct results, but there at least it slows down performance. It is also should be easy to break down into finer grained decompositions of the communication structure.
