### ISSUE TITLE
Gold_Standard regression test issues

### ISSUE THREAD

**Issue by kjeverson** [parthenon-hpc-lab/parthenon#445]
I am unable to download/untar the gold_standard regression tests properly. 

```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by JoshuaSBrown** [comment]
What command did you enter?

This works for me:

```
tar zxvf parthenon_regression_gold_v3.tgz 
x ./advection_2d.out0.00001.phdf
x ./advection_2d.out0.00001.phdf.xdmf
x ./advection_3d.out0.00001.phdf
x ./advection_3d.out0.00001.phdf.xdmf
x ./current_version
x ./outflow.out0.00001.phdf
x ./outflow.out0.00001.phdf.xdmf
x ./README.md
x .gitignore
```

**Comment by kjeverson** [comment]
I entered that exact command, but I also set the `-D REGRESSION_GOLD_STANDARD_SYNC=OFF`, otherwise I never get a matching hash

**Comment by JoshuaSBrown** [comment]
What is your checksum on the file? 

```
openssl md5 parthenon_regression_gold_v3.tgz 
MD5(parthenon_regression_gold_v3.tgz)= bb1302ab45d7e45e816eb70b762f0a3d
```

**Comment by kjeverson** [comment]
`MD5(parthenon_regression_gold_v3.tgz)= d41d8cd98f00b204e9800998ecf8427e`

**Comment by JoshuaSBrown** [comment]
It looks like you had a problem with the download. Can you try downloading again. https://github.com/lanl/parthenon/releases/tag/regression-gold-v3

**Comment by kjeverson** [comment]
That worked. Thanks!
