### ISSUE TITLE
Remove mention of `DerivedOwnership` from doc

### ISSUE THREAD

**Issue by jlippuner** [parthenon-hpc-lab/parthenon#455]
`DerivedOwnership` seems to have been removed (by @Yurlungur?), but the documentation (`docs/interface/state.md`) still mentions it.

**Comment by Yurlungur** [comment]
Good call. Yes that should be removed.

**Comment by INNeira** [comment]
Hi everyone. I'm new in github, this issue in particular will be my first if i can solve. Can i fix this? Thanks!

**Comment by Yurlungur** [comment]
Hi @INNeira welcome! Yes, please do. :)
