### ISSUE TITLE
Tiling when using Kokkos MDRange and others

### ISSUE THREAD

**Issue by JoshuaSBrown** [parthenon-hpc-lab/parthenon#466]
It will be worth finding reasonable defaults once the code base matures a bit more for the tiling parameter that can be specified alongside the different Kokkos policies. Using the defaults can lead to significant performance degradation.

**Comment by Yurlungur** [comment]
And this may be hardware or meshblock size dependent.

**Comment by pgrete** [comment]
Closing as this has been addressed in #487 
Feel free to reopen if performance is still not as expected.
