### ISSUE TITLE
Consecutive calls to cmake -S. -B build are failing on Darwin in some instances

### ISSUE THREAD

**Issue by JoshuaSBrown** [parthenon-hpc-lab/parthenon#471]
```
cmake -S. -B build
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
-- Could NOT find MPI (missing: MPI_CXX_FOUND CXX) 
    Reason given by package: MPI component 'Fortran' was requested, but language Fortran is not enabled.  

CMake Error at CMakeLists.txt:120 (message):
  MPI is required but couldn't be found.  If you want to build Parthenon
  without MPI, please rerun CMake with -DPARTHENON_DISABLE_MPI=ON


-- Configuring incomplete, errors occurred!
```

Seems to be a problem with finding mpi the second time around.

**Comment by Yurlungur** [comment]
That's odd. I wonder if there's an `include` guard or something that shouldn't be there?

**Comment by JoshuaSBrown** [comment]
I think I found the problem with this. I believe it is only happening on Darwin when the project space is being used because nvcc path is being added to the PATH env variable, so if you login again and try to run the build it will fail because it can't find the nvcc. The error message is misleading.

**Comment by JoshuaSBrown** [comment]
Ok, I can confirm this is the problem, this is Darwin specific cuda/11.0 needs to be loaded.
