### ISSUE TITLE
InitUserMeshData provides no access to `Mesh`

### ISSUE THREAD

**Issue by forrestglines** [parthenon-hpc-lab/parthenon#484]
The user hook for problem generation `InitUserMeshData` provides no access to `Mesh` or any physics packages. In the Athena++ implementation, `InitUserMeshData` was a member function of `Mesh` and so had acess to private data members. 

I think we could just add a `std::shared_ptr<Mesh> mesh` to the arguments of `InitUserMeshdata` to provide sufficient access to `Mesh`. However, we would have to change all the problem generators in downstream codes.

**Comment by pgrete** [comment]
Pinging @Yurlungur @jdolence @brryan @nmsriram for feedback regarding downstream implications.

**Comment by Yurlungur** [comment]
Wait---why would problem generators need to be modified? I don't think we currently use `InitUserMeshData` downstream. We just initialize everything we would need in the problem generator itself.

**Comment by forrestglines** [comment]
We often initialize all the additional multiphysics - for my problem different astrophysical feedback mechanisms, cooling, etc. - in the problem generator in `InitUserMeshData`. It's also usually the best place to call the user hooks like `EnrollUserExplicitSourceFunction`.  The (Athena++ docs)[https://github.com/PrincetonUniversity/athena-public-version/wiki/Problem-Generators] describe those use cases.

We would also like to include some mesh level coordination that is specific to certain problem generators, `InitUserMeshData` was the best place to do that in Athena++. We'd also like to try adding things to the `StateDescriptor` via the `Mesh` in `InitUserMeshData`. 

If `InitUserMeshData` isn't being used downstream, then the change should only affect us.

**Comment by Yurlungur** [comment]
I see. Ok. I think your suggested change might be useful for us down the road, but currently we don't use `InitUserMeshData`. We just stick things in scratch variables or `param`s.

**Comment by pgrete** [comment]
Closed via #498 and addressed downstream in packages.
