### ISSUE TITLE
Coverage failing

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#559]
Something is wrong with the coverage machinery:
https://gitlab.com/pgrete/parthenon/-/jobs/1414219182

@JoshuaSBrown @jlippuner @pgrete any ideas?

**Comment by pgrete** [comment]
I retriggered the job. Maybe there was a version mismatch. The job log reported version "1.0.3" but when I manually downloaded the file just now the version is supposed to be "1.0.4".

**Comment by jonahm-LANL** [comment]
Ah ok. Interesting. Fingers crossed then.


Sent from my phone. Please excuse typos.



From: Philipp Grete ***@***.******@***.***>>
Date: Monday, Jul 12, 2021, 6:14 AM
To: lanl/parthenon ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [lanl/parthenon] Coverage failing (#559)


I retriggered the job. Maybe there was a version mismatch. The job log reported version "1.0.3" but when I manually downloaded the file just now the version is supposed to be "1.0.4".

**Comment by pgrete** [comment]
Looks like this is fixed now: https://gitlab.com/pgrete/parthenon/-/jobs/1416960722
Potentially we just hit a bad moment where the script on the server was already updated but not yet the hash sums.

**Comment by JoshuaSBrown** [comment]
@pgrete thanks for the quick check.
