### ISSUE TITLE
Full Regression test suite currently failing due to sparse update

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#571]
As discussed on the Parthenon call. @jlippuner to fix.

**Comment by pgrete** [comment]
@jlippuner do you already know what's going on?
I saw that you started looking into this and I'm not sure I understand where the issue is.
On my machine the tests pass.

**Comment by jlippuner** [comment]
> @jlippuner do you already know what's going on?
> I saw that you started looking into this and I'm not sure I understand where the issue is.
> On my machine the tests pass.

Yes, I'm looking into it. I have a training workshop today, so might not be able to get to it until tomorrow. It's not clear to me either, what's going on. There's a difference in the "File" metadata attribute in the HDF5 file that's causing the issue. I added some verbose output in another branch to investigate further.

**Comment by jlippuner** [comment]
Alright, I see the issue. The tests are run with MPI on the CI machine, which adds the following default values to the input file:
```
<loadbalancing>
balancer  = default # Default value added at run time
tolerance = 0.5     # Default value added at run time
interval  = 10      # Default value added at run time
```
The gold files were generated without MPI and so they lack these entries.

We could just make `phdf_diff` ignore the `File` attribute and so it would not compare that the two sims were run with the same parameter file. But having that comparison may be useful. So maybe the better solution would be to write the default load balancing parameters to the file even when running without MPI. What do folks think?

**Comment by pgrete** [comment]
oh interesting, very subtle, that's what it passed locally (I also ran without MPI).
I'd say, let's also write those default parameters for serial runs because we can restart serial runs with MPI and vice versa. Thus, the output file should also be consistent from my point of view.

**Comment by Yurlungur** [comment]
I am fine with writing them in the file. That said, I lean towards ignoring this edge case in the tests. It bothers me that the tests are so brittle to these details.

**Comment by jlippuner** [comment]
Alright, I think I agree with both @pgrete and @Yurlungur. I'm changing it to always write the load balancing info, and I'm also turning off comparison of the File metadata by default. However, I've added an option to turn it on for debugging purposes (i.e. if one is trying to figure out why two files differ, one can turn on checking the input file contained in the HDF5 metadata and maybe that will help). See #575
