### ISSUE TITLE
Default load balancing options/behavior

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#576]
```c++
  if (pin->GetOrAddString("loadbalancing", "balancer", "default") == "automatic")
    lb_automatic_ = true;
  else if (pin->GetOrAddString("loadbalancing", "balancer", "default") == "manual")
    lb_manual_ = true;
```
I'm kind of surprised by this logic (but it's also in Athena++).
Looks like the "default" means neither "automatic" nor "manual". So if "automatic" is not default, what is?
I'll create an issue as it is unrelated to this PR.

_Originally posted by @pgrete in https://github.com/lanl/parthenon/pull/575#discussion_r677177156_

**Comment by Yurlungur** [comment]
`default` is just meshblock count. `automatic` is timers. `manual` is hand-introduced cost functions. I add documentation in #892
