### ISSUE TITLE
Possible bug in PackVariables call on MeshData objects

### ISSUE THREAD

**Issue by jdolence** [parthenon-hpc-lab/parthenon#579]
I haven't gotten to the bottom of this, but I think there might be a bug in the PackVariables machinery.  It seems like while this works:
```c++
myvar = std::vector<std:string>({"myvar"});
PackIndexMap imap;
auto v = md->PackVariables(myvar, imap);
// use v
```
this does not:
```c++
auto v = md->PackVariables(myvar);
```
i.e. the call where we don't ask for a PackIndexMap back seems to be broken.  Code compiles, but the answers are wrong.  For this single variable case, the index in the map should be (and is when explicitly pulled out) just zero.  So I had some code that called PackVariables without the PackIndexMap argument and then just hardcoded the zero index for the variable when I used the pack.  That code did not work.  Adding the PackIndexMap fixes the issue.  Don't have time to dig into this right now, but wanted to note this issue somewhere.

@jlippuner @Yurlungur @pgrete might all be interested.

**Comment by Yurlungur** [comment]
Oof. This might have been accidentally introduced in the recent changes to this machinery. I'll poke at it.

**Comment by Yurlungur** [comment]
@jdolence  what does the erroneous code return?

**Comment by jdolence** [comment]
Hard to describe.  A symptom was that a variable that was never supposed to be updated at all was changing mysteriously.

**Comment by Yurlungur** [comment]
I see. That helps.
