### ISSUE TITLE
Properly implement rank >= 2 variables

### ISSUE THREAD

**Issue by jlippuner** [parthenon-hpc-lab/parthenon#600]
Currently, we support variables scalar, vector, and tensor variables (up to rank 3) in principle. However, a lot of the infrastructure assumes that we only have rank-1 variables (i.e. scalars and vectors). I'm pretty sure that tensors would not currently work. I haven't dug deep, but for example most (if not all) functions in `amr_loadbalance.cpp` just use `CellVariable::GetDim(4)` to get the number of components, thus assuming that `GetDim(5) == GetDim(6) == 1`, which would be false for rank-2 and rank-3 tensor variables.

**Comment by pgrete** [comment]
Good point. As an immediate step, shall we add sth that makes the code fail if that kind of variable is added?
Just to be sure that no one starts experimenting with downstream piece assuming everything works as is?

**Comment by Yurlungur** [comment]
Please don't add such a check. We are experimenting with such machinery downstream. If we can pepper places we thinks thing will fail with warnings, that might be useful though.

**Comment by Yurlungur** [comment]
Ping @lroberts36

**Comment by pgrete** [comment]
> Please don't add such a check. We are experimenting with such machinery downstream. If we can pepper places we thinks thing will fail with warnings, that might be useful though.

Even better. If some is already experimenting then this might get fixed sooner than later.

**Comment by lroberts36** [comment]
I am starting to put radiation moments into Phoebus, and this requires some variables of rank-2 (and maybe rank-3 if extended to multi-group). I haven't run into any issues yet, but the development on this just started.

**Comment by lroberts36** [comment]
Ok, I just ran into a problem with HDF5 output of rank-2 fields. For instance, I have a variable field defined in Phoebus that has a shape of (3, nSpecies), so naively I would expect an HDF5 dataset with dimensions (nblocks, nz, ny, nx, 3, nSpecies) or (nblocks, nz, ny, nx, 3*nSpecies). The output dataset has the dimension (nblocks, nx, ny, nx, 3).

**Comment by jlippuner** [comment]
> Ok, I just ran into a problem with HDF5 output of rank-2 fields. For instance, I have a variable field defined in Phoebus that has a shape of (3, nSpecies), so naively I would expect an HDF5 dataset with dimensions (nblocks, nz, ny, nx, 3, nSpecies) or (nblocks, nz, ny, nx, 3*nSpecies). The output dataset has the dimension (nblocks, nx, ny, nx, 3).

Yes, that's one of many issues. In a lot of places, we just do `GetDim(4)` and assume that dim 5 and 6 are 1. For the output, I'm actually fixing this in #586 (and it will be 3*nSpecies). But there are lots of other places in the infrastructure that don't support rank 2 and above.

**Comment by Yurlungur** [comment]
It looks like rank < 1 also causes a problem. See #606. @jlippuner does your sparse PR fix this too?

**Comment by Yurlungur** [comment]
Resolved long ago
