### ISSUE TITLE
RFC: Allow modification of `dt` in `PreStepUserWorkInLoop`

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#601]
`PreStepUserWorkInLoop` is currently a `std::function<void(Mesh *, ParameterInput *, SimTime const &)>`.
Any objection to remove the `const` from the `SimTime` parameter?

The rationale is that I'm currently working on a super timestepping algorithm for parabolic terms where there's a practical "correctness" limit on the super timestep (despite not having a stability limit for the super timestep).
In order to calculate the parabolic timestep I modified our `EstimateTimestep` function that calculate all timesteps but does not return the parabolic timestep as minimum but instead saves it in the package `Params`.
In that function only the rank local blocks are handled and the overall MPI reduction for `dt` occurs in Parthenon only after `Step()` in the driver. 
However, that only applies to the single `dt` returned from that function so I added another reduction for `dt_par` in `PreStepUserWorkInLoop`.
Given the practical constraint on `dt_par` I want to have the opportunity to limit the actual `dt`, which is currently not possible because `SimTime` is `const`.

I'm also open to other suggestions in terms of implementation, but on first sight it looks like the cleanest and generally most flexible solution to me without additional interfaces/machinery in Parthenon.

Thoughts from downstream developers? Ping @Yurlungur @jdolence @brryan

**Comment by Yurlungur** [comment]
No objections from my end. Doing this by modifying `SimTime` feels a little messy. But I don't see a better solution.
