### ISSUE TITLE
Output does not support variables with reduced rank

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#606]
@nmsriram and I recently tried to register a variable not tied to grid topology (e.g., with `Metadata::None`) and shape something like `5x1x1x1x1x1`. This *can* be registered. And for the types of things you might want this for, e.g., per-meshblock scratch space of some kind, it works fine. However, the I/O doesn't capture it. Instead, the output shape is always as if it were a cell variable.

Probably related to #600 . Pinging @jlippuner

**Comment by jlippuner** [comment]
Hmm, no I don't think so. Currently, the HDF5 I/O assumes that all variables written are cell variables.

**Comment by Yurlungur** [comment]
Resolved
