### ISSUE TITLE
Const correctness in Params

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#621]
I have a heretical suggestion: `params` should not return a const reference. It should just return a reference. We are already using `params` for non-const objects, namely containers. We're fooling the `const` correctness by just hiding things behind `Kokkos::Views`. Since we're not obeying the spirit of `const`, why are we obeying the letter?

This is also relevant for things like global reductions. I recently discovered that I can't hide a `Reduce<T>` object in `Params` without putting it inside a `Kokkos::View` because `const` correctness prevents me from calling the reducer methods, but I need the object to persist---it can't be a copy.

Interested in what people think.

**Comment by brryan** [comment]
In the situation where a large number of packages maintained by different developers are all interacting through the same driver, I can see the advantages of being able to set parameters to be constant (it'd be nice if this could be enforced for data in `View`s as well). 

But it seems clear to me that a `params`-like bin for non-`const` data is needed. Like you say we already use it. In my mind the optimal solution is a genuinely-`const` `params` and a separate non-`const` entity called `PackageData` or something. Existing non-constant data in params could gradually be migrated (or not)

**Comment by Yurlungur** [comment]
Hmm this gives me an idea, @brryan . I think we can easily do both with a single object and minimal code surgery. Check out PR #623.
