### ISSUE TITLE
Need 2022 copyright update

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#632]

**Comment by pgrete** [comment]
@Yurlungur @lroberts36 @brryan @jdolence 
As far as I can tell the current infrastructure should pick the current year automatically
https://github.com/lanl/parthenon/blob/f3d5432c0406a421b30799d7508db639cdb0d8f2/cmake/CheckCopyrightScript.cmake#L22
Could you please confirm that the script actually works (and, if yes, close the issue)? I haven't seen this check being triggered for quite some time and (due to lack of @lanl.gov address) cannot check myself.

**Comment by Yurlungur** [comment]
It works and all copyrights currently are up to date.
