### ISSUE TITLE
Are we properly incrementing `phys_id`?

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#660]
I dug deeper into the issue that was raised during yesterday's call.

Here's what I found so far:
In the original Athena++ implementation, the physical ids for "standard" variables (e.g., hydro or b-fields) were implicitly updated in the constructor of various "physics", e.g., in `meshblock.cpp`
```c++
    phydro = new Hydro(this, pin);
    pbval->AdvanceCounterPhysID(HydroBoundaryVariable::max_phys_id);
  if (MAGNETIC_FIELDS_ENABLED) {
    pfield = new Field(this, pin);
    pbval->AdvanceCounterPhysID(FaceCenteredBoundaryVariable::max_phys_id);
  }
```
the `Hydro` and `Field` constructors would use the *current* `next_phys_id` (private var of the `MeshBlock`) for setting up the boundary variables.
The ids are *not* updated when they are assigned to the bvars, but afterwards manually incremented (by some const. max value).

*We don't call `AdvanceCounterPhysID` anywhere...

At the `Mesh` level Athena++ also has (and calls) `ReserveTagPhysIDs` in order to set a mesh level id (mesh private `next_phys_id`) so that other, extra  physics that need boundary comm start with a proper offset for the tags.

Given that from a Parthenon point of view everything is "extra" (as in separate packages), we don't need two separate functions, but need to ensure that we always advance the id for all kind of `Variables`.

Some dirty debugging in Parthenon with 
```diff
diff --git a/src/bvals/cc/bvals_cc.cpp b/src/bvals/cc/bvals_cc.cpp
index a22b0ed0..04bfc526 100644
--- a/src/bvals/cc/bvals_cc.cpp
+++ b/src/bvals/cc/bvals_cc.cpp
@@ -66,6 +66,7 @@ CellCenteredBoundaryVariable::CellCenteredBoundaryVariable(std::weak_ptr<MeshBlo
   // KGF: dead code, leaving for now:
   // cc_phys_id_ = pmb->pbval->ReserveTagVariableIDs(1);
   cc_phys_id_ = pmb.lock()->pbval->bvars_next_phys_id_;
+  std::cout << label << " uses id " << cc_phys_id_ << std::endl;
 #endif
   if (pmy_mesh_->multilevel) { // SMR or AMR
     InitBoundaryData(bd_var_flcor_, BoundaryQuantity::cc_flcor);
```
with the advection example and `Advection/num_vars=2`:
```
advected uses id 1
advected_1 uses id 1
advected uses id 1
advected_1 uses id 1
advected uses id 1
advected_1 uses id 1
...
```
not great.

I assume that this hasn't caused any bugs because the packing machinery has mostly been used with a single pack per rank and everything was well ordered (so even if two messages were send with the same tag for two different variables the receiving function were also in the same order).
This would also be connected to the intermittent MPI errors that Jonas saw when he implemented sparse variables.

A first fix 
```diff
diff --git a/src/bvals/cc/bvals_cc.cpp b/src/bvals/cc/bvals_cc.cpp
index a22b0ed0..491e6e79 100644
--- a/src/bvals/cc/bvals_cc.cpp
+++ b/src/bvals/cc/bvals_cc.cpp
@@ -63,14 +63,14 @@ CellCenteredBoundaryVariable::CellCenteredBoundaryVariable(std::weak_ptr<MeshBlo
   InitBoundaryData(bd_var_, BoundaryQuantity::cc);
 
 #ifdef MPI_PARALLEL
-  // KGF: dead code, leaving for now:
-  // cc_phys_id_ = pmb->pbval->ReserveTagVariableIDs(1);
-  cc_phys_id_ = pmb.lock()->pbval->bvars_next_phys_id_;
+  cc_phys_id_ = pmb.lock()->pbval->AdvanceCounterPhysID(1);
+  std::cout << label << " uses id " << cc_phys_id_ << std::endl;
 #endif
   if (pmy_mesh_->multilevel) { // SMR or AMR
     InitBoundaryData(bd_var_flcor_, BoundaryQuantity::cc_flcor);
 #ifdef MPI_PARALLEL
-    cc_flx_phys_id_ = cc_phys_id_ + 1;
+    cc_flx_phys_id_ = pmb.lock()->pbval->AdvanceCounterPhysID(1);
+    std::cout << label << " flx uses id " << cc_flx_phys_id_ << std::endl;
 #endif
   }
 }
```
resulting in some interesting behavior:
```
advected_1 uses id 1
advected_1 flx uses id 2
advected uses id 3
advected flx uses id 4
advected_1 uses id 1
advected_1 flx uses id 2
advected uses id 3
advected flx uses id 4
cycle=3 time=5.2734375000000003e-03 dt=1.7578125000000000e-03 zone-cycles/wsec_step=5.02e+06 wsec_total=2.20e-02 wsec_step=4.49e-03 zone-cycles/wsec=3.50e+06 wsec_AMR=1.96e-03
-------------- New Mesh structure after (de)refinement -------------
Root grid = 4 x 4 x 1 MeshBlocks
Total number of MeshBlocks = 94
Number of physical refinement levels = 2
Number of logical  refinement levels = 4
  Physical level = 0 (logical level = 2): 3 MeshBlocks, cost = 3
  Physical level = 1 (logical level = 3): 39 MeshBlocks, cost = 39
  Physical level = 2 (logical level = 4): 52 MeshBlocks, cost = 52
--------------------------------------------------------------------
advected_1 uses id 5
advected_1 flx uses id 6
advected uses id 7
advected flx uses id 8
advected_1 uses id 9
advected_1 flx uses id 10
advected uses id 11
advected flx uses id 12
```
I don't understand yet where the ids >4 are coming from.

**Comment by pgrete** [comment]
I dug deeper.
ids > 5 come from the non-shallow copies in the driver
```c++
      for (int i = 1; i < integrator->nstages; i++)
        pmb->meshblock_data.Add(stage_name[i], base);
```

So the question now is what's the right fix.
I remember that "some" time (>1 year) we talked about sharing (or not) communicators between stages.
IIRC we decided that there should only be one shared bvals object independent of the number of stages.
Is my recollection correct?
Specifically pinging @jdolence @Yurlungur @lroberts36

**Comment by Yurlungur** [comment]
Thanks for digging into this, @pgrete ! 

I think we only need one communicator shared between all stages. So if the communicators were shallow copied that would resolve the issue.

I think @lroberts36  has also been looking at rewriting this so we should coordinate a fix.

**Comment by pgrete** [comment]
More digging:

Looks like the non-shallow copy indeed reused the original bvars
https://github.com/lanl/parthenon/blob/1d72227179ce2e34dcba9736587c0f167326d32b/src/interface/variable.cpp#L120
but only after a new bvars object has been created.

This is a bug, which should have been caught by
https://github.com/lanl/parthenon/blob/1d72227179ce2e34dcba9736587c0f167326d32b/src/interface/variable.cpp#L52
but I think the error check is wrong as there should have been a `==` instead of a `,` when comparing the pointers.

**Comment by Yurlungur** [comment]
Whoops! Well this is a good catch. And presumably easy to fix to force a shallow copy.

**Comment by pgrete** [comment]
More digging:
https://github.com/lanl/parthenon/blob/1d72227179ce2e34dcba9736587c0f167326d32b/src/interface/variable.cpp#L194
Why is this (and the following check) happening there?
`vbvar` is "allocated" in the constructor of the CellVariable itself.

**Comment by Yurlungur** [comment]
I understood that at one point... If I recall, the old physical boundaries machinery was per meshblock and registered a bunch of variables to it. (We probably want to invert that logic.)

This call registers the variable to the bvars object.

**Comment by Yurlungur** [comment]
Maybe I misunderrstood... but `bval` is owned by the meshblock right? And `bval` points at a list of `bvar`s. This is adding the `bvar` for the cell variable to the `bval` object of the meshblock.

It's only needed for boundary communication, which is why it's there, I think.

**Comment by pgrete** [comment]
Here's a first attempt trying to be logically consistent, i.e., the vbar object is created only at a single place `AllocateFluxesAndBdryVar` (and cleaning up some dead code).
The relevant parts are:
https://github.com/lanl/parthenon/pull/661/files#diff-bc7162b12498bffe2fd41b97efd9c5e06fe7895c2c966a91180b6269da05bf1c
and 
https://github.com/lanl/parthenon/pull/661/files#diff-b67052ba143139223cd63f71c046ef3077eb5220851e04afbb273fd64c30c956
