### ISSUE TITLE
`test_unit_sort.cpp` compilation hangs on some platforms

### ISSUE THREAD

**Issue by brryan** [parthenon-hpc-lab/parthenon#672]
On power9 and another GPU node both @lroberts36 and I have experienced compilations hang on `tst/unit/test_unit_sort.cpp`. Commenting out the `GIVEN` block allows compilation to proceed.

**Comment by pgrete** [comment]
Without the `GIVEN` the entire test is removed, isn't it?
Have you tried updating to the latest version of catch2?

**Comment by lroberts36** [comment]
@brryan @pgrete : It looks like this might be an issue with `thrust::sort` (see https://github.com/NVIDIA/cccl/issues/754). If I comment out the calls to `thrust::sort` in `sort.hpp` (which is obviously not a solution to the problem), the compile time for `test_unit_sort` is reasonable.

**Comment by brryan** [comment]
Interesting, thanks for sharing -- it seems like this issue causes compile times to scale with complexity of the comparator but in the unit test it's a simple `<`. On a hunch, I tried changing the sorted `value` from `char value_[STRLEN]` to `int` and this seems to solve the compile time issue. Surprising but I think this is a reasonable fix for this annoying problem -- I'll put a PR up in a second

**Comment by lroberts36** [comment]
Fixed in NVIDIA/thrust#680
