### ISSUE TITLE
Output component naming

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#684]
After the merge #679 reading AthenaPK data is broken because we have another edge case.

Our main variables are stored in a single field, but it's not a vector in the mathematical/physical sense.
Therefore the change introduced by the PR
```c++
    if (vlen == 1 || is_vector) {
      component_labels = component_labels_.size() > 0 ? component_labels_
                                                      : std::vector<std::string>({label});
    } else {
      for (int i = 0; i < vlen; i++) {
        component_labels.push_back(
            label + "_" +
            (component_labels_.empty() ? std::to_string(i) : component_labels_[i]));
      }
    }
``` 
results in the components being labelled as
```hdf5
         DATASPACE  SIMPLE { ( 5 ) / ( 5 ) }
         DATA {
         (0): "prim_Density", "prim_Velocity1", "prim_Velocity2",
         (3): "prim_Velocity3", "prim_Pressure"
         }
```

One easy fix would be to adjust the analysis tools (e.g., `yt`) to use the new field names.
However, I'm not sure if the current behavior is the desired behavior.
From a downstream developer point of view, I'd naively expect that if I provide an array/vecor with labels for all components then these are the desired labels.
Therefore, I'm currently in favor of not making compound names in case a developer has specified names for all components.

Any thoughts? @brryan @Yurlungur @forrestglines

**Comment by Yurlungur** [comment]
The ability to automatically group vectors is useful for us downstream. What about a metadata solution, where physical vector is distinguished from a grouping as in AthenaPK?

**Comment by pgrete** [comment]
Maybe I misunderstood the original issue, but I was/am only concerned about the label used in the output file (not internally).
Here's a suggested quick fix: https://github.com/lanl/parthenon/pull/688
It uses the given component labels if they are provided for all component and otherwise create compound labels from the `label` with the index.
Does this work with/fix the original issue issue in Phoebus?

**Comment by Yurlungur** [comment]
Yeah that should work fine for us I think.
