### ISSUE TITLE
Kokkos 3.6.01

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#705]
Are there any objections to bump Kokkos to 3.6.01 early next week after the new release?
This will
- improve HIP and SYCL backend (I'm actually using newer Kokkos version for the tests on Frontier)
- introduce `KOKKOS_IF_ON_{HOST/DEVICE}` macros that will be useful, for example, in #663 or in AthenaPK downstream

This
- should not have an impact on the current Parthenon codebase (apart from improvements)
- does NOT imply a bump to C++17 (which will first happen with the 3.7 release that currently has a release candidate out)

Ping @jdolence @Yurlungur @lroberts36 @brryan

**Comment by Yurlungur** [comment]
No objections from me. I think this a good idea.

**Comment by lroberts36** [comment]
This certainly seems like a good fix for the cuda macro that is currently used in #663.
