### ISSUE TITLE
Metrics App CI failed

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#723]
Can someone at LANL please check why current `develop` failed: https://re-git.lanl.gov/eap-oss/parthenon/-/jobs/536301
Ping @jdolence @Yurlungur @brryan @lroberts36

**Comment by lroberts36** [comment]
@pgrete It looks like the `advection_outflow` tests and the `poisson` tests are failing because of a mismatch in the `OutputFormatVersion` attribute in the hdf5 output. We could either update the gold files or ignore this attribute in the hdf5 diff, I would vote for the latter.
