### ISSUE TITLE
plans for Ascent support?

### ISSUE THREAD

**Issue by BenWibking** [parthenon-hpc-lab/parthenon#728]
Hi,

Are there any plans to add support for using Ascent for in-situ visualization?

Thanks,
Ben

**Comment by pgrete** [comment]
In-situ viz (and analysis) is on our wish-list (and becoming more and more pressing).
We'll discuss during the developer workshop next week.
If you have specific guidance, experience, requirements,... please share so that we can take those into account.

**Comment by BenWibking** [comment]
I've added Ascent support to Quokka, but the difficult part was already done in AMReX (constructing the data structures for the AMR grids). For me, the important features are slice plots, mostly to check if the simulation is still doing something reasonable (and also for making high-time-resolution movies), and outputting text files with summary statistics from VisIt-like expressions (that are JIT-compiled). Low memory usage and avoiding having to run a full copy of VisIt or Paraview are also very important.

Overall, Ascent works well. It can be a pain to build due to the large number of dependencies, but the build process has improved significantly recently. One thing it doesn't support as a built-in feature is the ability to do projection plots like in yt (there is a workaround, but it's cumbersome). I think it's most useful feature is the ability to specify the plots and summary statistics in a YAML file that you can edit as a simulation is running to adjust what you're getting.

The outstanding bugs that affect my work are i) it doesn't render correctly if you don't include the ghost zones in the data passed to Ascent (at least for AMReX sims) ii) it doesn't render at all if you give it box sizes that are too large to be represented in single precision float (this is actually a VTK-m bug, so I just rescale to the unit box before passing to Ascent) iii) the volume rendering for AMR grids currently has artefacts at grid boundaries (not clear what is causing this).
