### ISSUE TITLE
Names for the parthenon github project

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#745]
Drop your suggestions or vote on them with 👍 here.

**Comment by Yurlungur** [comment]
My suggestion: Parthenon-AMR

**Comment by Yurlungur** [comment]
Another suggestion: parthenon-project

**Comment by pgrete** [comment]
parthenon-code

**Comment by pgrete** [comment]
parthenon-org

**Comment by pgrete** [comment]
parthenon-collaboration

**Comment by pgrete** [comment]
parthenon-group

**Comment by pgrete** [comment]
parthenon-team

**Comment by jdolence** [comment]
parthenon-collab

**Comment by jdolence** [comment]
parthenon-consortium

**Comment by lroberts36** [comment]
parthenon-league

**Comment by jdolence** [comment]
parthenon-thread

**Comment by Yurlungur** [comment]
parthenon-device-kernel

**Comment by Yurlungur** [comment]
the-best-parthenon

**Comment by tagardiner** [comment]
parthenon-best-of

**Comment by Joseph-Weller** [comment]
parthenon-not-the-building

**Comment by Joseph-Weller** [comment]
Parthenon-HPC-Collab

**Comment by jdolence** [comment]
parthenon-hpc-lab

done
