### ISSUE TITLE
Update to C++17

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#746]
We all agreed we should do this. The relevant TODOs:
- [ ] Update Kokkos tag
- [ ] Update CMake
- [ ] Update Readme and documentation
- [ ] Cleanup code

**Comment by pgrete** [comment]
I suggest to not just go to Kokkos 3.7 yet without additional testing.

Basic pieces are updated in #758 but I a more general "cleanup" is still "tbd" (so I added it above to the checklist).

**Comment by Yurlungur** [comment]
Resolved as we have updated
