### ISSUE TITLE
Dependent PRs

### ISSUE THREAD

**Issue by c-prather** [parthenon-hpc-lab/parthenon#776]
It seems like we pretty often open PRs that depend on other still-open PRs -- a necessary consequence of a small team working closely, I think.

It would be nice if we could mark these dependencies in a formal way, to avoid accidentally merging PRs prematurely.  Github doesn't allow this natively, but something like [dpulls](https://www.dpulls.com/) might be easy enough to set up.  It just auto-scans the PR comment for "Depends on", a bit like the current WIP bot.

Happy to try to set this up if folks would be interested.

**Comment by Yurlungur** [comment]
This is cool. I'd be interested.

**Comment by pgrete** [comment]
Yes, I also like the idea.
Is there potentially a GitHub action that could be used? (Given that we use self-hosted runners, I prefer to not give external services direct access to the repos).

**Comment by lroberts36** [comment]
This definitely seems like it would be a useful thing to have.

**Comment by c-prather** [comment]
Opened #777 .  I'm not sure how the tokens for actions work, if we wanted to issue a minimal one it would only need read access to PRs and Issues.

**Comment by Yurlungur** [comment]
I don't think we need to issue a token manually. I think that happens automatically. I think there was a different permissions error. Can you try again?

**Comment by Yurlungur** [comment]
Ah problem solved

**Comment by c-prather** [comment]
#777 is merged.  I should have said "fixed in" so GitHub would close this.
