### ISSUE TITLE
Do Prolongation/Restriction Need Knowledge about Other Variables?

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#779]
Related to #769 . 

@bprather points out that the prolongation/restriction operators do not have information about what variables they are, or have access to other variables that have been registered. For things like "primitive prolongation" or "upwinding" this may need re-visiting. 

That said that would be a deeper change, either requiring boundary packing to work on meshblockpacks explicitly or requiring `ParArrayNDGeneric` to carry around additional information. I suggest that this change be revisited as needed in a separate PR.

**Comment by c-prather** [comment]
It looks like I was wrong about most UCT/AMR schemes.

The inter-variable dependencies show up only for the CT step, in calculating the EMFs.  This step depends at least on the wave speeds and fluid velocities on the face.

However, nothing so complex is needed for prolongation and restriction themselves.  Certainly, restriction is (I think) always done in the obvious way, summing fine cells.

When prolongating, exterior faces seem to be chosen via slope estimations & optionally minmod, never anything special.  Interior faces, however, are chosen purely to preserve the divergence-free constraint.  This leaves (depending on priorities) 3 free parameters, which can be chosen a number of ways.  However, I don't think any reasonable scheme for this involves reading other fluid variables -- at worst they read geometry & a truly nasty number of adjacent zone fluxes.

So, I'd say this is moot until someone finds a crazy use case where we need to revisit it.  The field dependency and grouping plumbing, however, I think should move forward as a separate issue: it would present a natural way to add callbacks for floors and boundaries to Parthenon, or even just Parthenon-based codes.

Note I'm referring mostly to the explanations from [here](https://arxiv.org/abs/1906.10795).

**Comment by Yurlungur** [comment]
Sounds good. Thanks for following up. I'll close this for now.

**Comment by c-prather** [comment]
Pinging @pgrete if he wants to reopen, since this is where the prior discussion was of (I think) a very similar enhancement need.
