### ISSUE TITLE
where to find grid metadata

### ISSUE THREAD

**Issue by BenWibking** [parthenon-hpc-lab/parthenon#789]
I'm planning to implement basic Ascent support (i.e., cell-centered fields, no sparse variables). It looks pretty straightforward, but I'm not super familiar with how to find all the metadata for each grid in Parthenon.

Following https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#coordinate-sets, for each grid, I need:
1. the location of the lower-left corner (x,y,z)
2. the grid spacing (dx, dy, dz)
3. the number of cells (nx, ny, nz)
4. a pointer to the (hopefully contiguous) cell-centered data for a given field on a grid

Could someone point me where to access each of these? Thanks!

**Comment by Yurlungur** [comment]
By `grid` here I assume you mean `meshblock` in Parthenon parlance? Most of this information is stored in either the `IndexShape` object or in the `Coordinates_t` object. Both are available per-meshblock. Both are available per-meshblock as the `cellbounds` and `coords` fields of the `MeshBlock` class. However, a more common, parthenon-ic way of doing this is to interact with `MeshData` and `MeshBlockPack` to extract them. For example, here's a code snippet from the Burgers' equation solver that @jdolence just wrote. (See [here](https://github.com/parthenon-hpc-lab/parthenon/tree/develop/benchmarks/burgers) for the full solver.)
```C++
Real EstimateTimestepMesh(MeshData<Real> *md) {
  Kokkos::Profiling::pushRegion("Task_burgers_EstimateTimestepMesh");
  auto pm = md->GetParentPointer();
  IndexRange ib = md->GetBoundsI(IndexDomain::interior);
  IndexRange jb = md->GetBoundsJ(IndexDomain::interior);
  IndexRange kb = md->GetBoundsK(IndexDomain::interior);

  auto &params = pm->packages.Get("burgers_package")->AllParams();
  const auto &cfl = params.Get<Real>("cfl");

  std::vector<std::string> vars({"U"});
  auto &v = md->PackVariables(vars);
  const int ndim = pm->ndim;

  Real min_dt;
  parthenon::par_reduce(
      parthenon::loop_pattern_mdrange_tag, "burgers::EstimateTimestep", DevExecSpace(), 0,
      md->NumBlocks() - 1, kb.s, kb.e, jb.s, jb.e, ib.s, ib.e,
      KOKKOS_LAMBDA(const int b, const int k, const int j, const int i, Real &ldt) {
        auto &coords = v.GetCoords(b);
        ldt = std::min(
            ldt,
            1.0 /
                ((std::abs(v(b, 0, k, j, i))) / coords.Dx(X1DIR, k, j, i) +
                 (ndim > 1) * (std::abs(v(b, 1, k, j, i))) / coords.Dx(X2DIR, k, j, i) +
                 (ndim > 2) * (std::abs(v(b, 2, k, j, i))) / coords.Dx(X3DIR, k, j, i)));
      },
      Kokkos::Min<Real>(min_dt));

  Kokkos::Profiling::popRegion(); // Task_burgers_EstimateTimestepMesh
  return cfl * min_dt;
}
```
This a common pattern which gets you most of what you need. Let me walk you through some pieces:
```C++
IndexRange ib = md->GetBoundsI(IndexDomain::interior);
```
`GetBounds*` returns an `IndexRange` struct, which contains two fields `s` and `e` which are the inclusive loop bounds for the domain specified in the drection specified. You can specify `IndexDomain::interior` to exclude ghost cells and `IndexDomain::entire` for the whole meshblock. (All meshblocks are the same logical shape so you can request this information mesh-wide.)

So one way of getting total number of cells in the `X1` direction is `ib.e - ib.s + 1`. For example. (There are other ways of accessing this information but this way is probably easiest in this example.)

The next thing I want to bring your attention to is this block:
```C++
  std::vector<std::string> vars({"U"});
  auto &v = md->PackVariables(vars);
```
this packs all the variables listed in the `vars` object into a single index space, here referred to as `v`. The slowest moving index is meshblock, the next-slowest is variable, then `k,j,i`. So for example `v(b, f, k, j, i)` is the cell-centered data for field f on block b at k, j, i. There are two ways to name the index f here, one of which is documented [here](https://github.com/parthenon-hpc-lab/parthenon/blob/develop/docs/interface/containers.md). (The other, newer way was developed by @lroberts36 but I can't find the documentation. Luke can you point to the documentation on sparse packs?)

If you wish to avoid pointer chasing, the `k,j,i` piece of the pack is always contiguous. So you could pull it out via, e.g., `&v(b, f, 0, 0, 0)`. 

The coords object per block is also provided by the pack. For example with
```C++
auto &coords = v.GetCoords(b)
Real dx1 = coords.Dx(X1DIR, k, j, i);
```
and for uniformly spaced meshes `Dx` is the same for all k, j, i. The lower left corner is just 
```C++
Real corn[] = {coords.x1f(ib.s), coords.x2f(jb.s), coords.x3f(kb.s)}
```
where `ib`, `jb`, and `kb` are pulled from above. Including or excluding ghosts as appropriate.

By the way, broadly you may want to look at the burgers equation example as it will probably be useful:
https://github.com/parthenon-hpc-lab/parthenon/tree/develop/benchmarks/burgers
or at parthenon-hydro:
https://github.com/parthenon-hpc-lab/parthenon-hydro

Does this all answer your question? Others should chime in if they have more to add.

**Comment by BenWibking** [comment]
Yes, I meant `meshblock`. I think that answers everything. I'll come back with questions if there's something else I missed.
