### ISSUE TITLE
CI broken?

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#798]
For #769 , I'm seeing some bizarre errors on the CI that don't look like code issues but CI configuration:
https://github.com/parthenon-hpc-lab/parthenon/actions/runs/3609553944/jobs/6083261172

@pgrete do you have any insight? Looks like nvidia driver mismatch on the container maybe?

**Comment by pgrete** [comment]
Hmm, my first guess is that some nvidia drivers/libs were updated on that machine but the services/modules not properly reloaded.
I'll ask our admin.

**Comment by pgrete** [comment]
My guess was correct. CI should be up and running again.
