### ISSUE TITLE
AMR prolong/restriction may not work for rank >=2 variables

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#825]
Looking at the final changes in #818 I noticed https://github.com/parthenon-hpc-lab/parthenon/blob/b866f72e80b7fa6133bdcf4ca3cd65d6df276235/src/mesh/amr_loadbalance.cpp#L1033

On first sight, this looks like it may be an issue for rank >= 2 variables as the data is not packed but directly accessed.
Do you agree @Yurlungur @lroberts36 @pdmullen ?

This probably also applies to
https://github.com/parthenon-hpc-lab/parthenon/blob/b866f72e80b7fa6133bdcf4ca3cd65d6df276235/src/mesh/amr_loadbalance.cpp#L510
https://github.com/parthenon-hpc-lab/parthenon/blob/b866f72e80b7fa6133bdcf4ca3cd65d6df276235/src/mesh/amr_loadbalance.cpp#L872
https://github.com/parthenon-hpc-lab/parthenon/blob/b866f72e80b7fa6133bdcf4ca3cd65d6df276235/src/mesh/amr_loadbalance.cpp#L940
https://github.com/parthenon-hpc-lab/parthenon/blob/b866f72e80b7fa6133bdcf4ca3cd65d6df276235/src/mesh/amr_loadbalance.cpp#L976
https://github.com/parthenon-hpc-lab/parthenon/blob/b866f72e80b7fa6133bdcf4ca3cd65d6df276235/src/mesh/amr_loadbalance.cpp#L1084
https://github.com/parthenon-hpc-lab/parthenon/blob/b866f72e80b7fa6133bdcf4ca3cd65d6df276235/src/mesh/amr_loadbalance.cpp#L1130
https://github.com/parthenon-hpc-lab/parthenon/blob/b866f72e80b7fa6133bdcf4ca3cd65d6df276235/src/mesh/amr_loadbalance.cpp#L1204
https://github.com/parthenon-hpc-lab/parthenon/blob/b866f72e80b7fa6133bdcf4ca3cd65d6df276235/src/mesh/amr_loadbalance.cpp#L1247

**Comment by lroberts36** [comment]
Yes, I agree. I noticed this issue as well when I was making changes in #818. I started thinking about how to fix it and then got sidetracked. @pdmullen: Are you using tensor variables in your radiation solver?

**Comment by Yurlungur** [comment]
Yeah this is descended from the original design. Definitely needs an update.

**Comment by pdmullen** [comment]
> Yes, I agree. I noticed this issue as well when I was making changes in #818. I started thinking about how to fix it and then got sidetracked. @pdmullen: Are you using tensor variables in your radiation solver?

I am not using tensorial variables.
