### ISSUE TITLE
Movie python script not working

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#832]
Trying to use the movie script (which I haven't used in ages) for a 2D problem with mesh refinement, I got 

![0000](https://user-images.githubusercontent.com/22685568/218142210-ea63777e-4bda-471b-ab28-b697460c7079.png)

whereas I expected sth like

![image](https://user-images.githubusercontent.com/22685568/218142287-c43260f6-524d-4af5-9be3-4d8d75046111.png)

**Comment by Yurlungur** [comment]
Wow okay well that's certainly an issue. I thought I used this script recently and it worked ok... but the I/O has changed a bit so... perhaps something is off.

**Comment by Yurlungur** [comment]
Agree about regression testing for Python. I found the issue here. When outputs changed to support tensor shapes, the movie2d script was not prepared for that. I need the script currently so I'll submit a fix.

**Comment by pgrete** [comment]
I can confirm that #833 fixes this issue. Updated plot with the script looks like
![0000](https://user-images.githubusercontent.com/22685568/218672265-c9d1bfd1-0433-46d8-8624-48005f045ad7.png)
