### ISSUE TITLE
Implicit conversions for `FlagCollection`

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#839]
cpplint enforces that single-argument constructors be marked explicit. This doesn't make sense in a heavily templated code because, for example, what is the meaning of marking this explicit?
```C++
template<typename T>
MyClass(const T &arg)
```
worse, marking it `explicit` breaks template resolution, as I discovered in #831 when trying to implement a simpler constructor based on @lroberts36 's simple concepts machinery. I suggest we remove this check from our copy of cpplint. (However, I wanted to make an issue, rather than just do it, as I think this one merits collaboration consensus.)

**Comment by lroberts36** [comment]
I support removing this requirement from the linter.

**Comment by pgrete** [comment]
Do we want/need/rely on implicit conversions at the moment?

Given the example above, I even think that we want the explicit keyword as otherwise we'd allow any kind of implicit type conversion for that class (or I am missing sth).

**Comment by Yurlungur** [comment]
> Do we want/need/rely on implicit conversions at the moment?

I hit this because I wanted to use @lroberts36 simple concepts for a single argument constructor and the linter didn't like it.

> Given the example above, I even think that we want the explicit keyword as otherwise we'd allow any kind of implicit type conversion for that class (or I am missing sth).

I'm not sure I follow, allowing an unconstrained template argument into the constructor *already* allows essentially the same thing as any kind of implicit type conversion. What I'd like to do is enforce what types are allowed in via a C++ concept.

**Comment by pgrete** [comment]
I'm fully in favor of concepts to control the allowed types, but I probably still don't fully understand the issue.

How does the intended code compare to the following snippet? 

```c++
struct Foo { };

template<typename T>
struct Baz {
  Baz(T t) {};
};

template<typename T>
void fun(T t) {};

int main() {
  Foo foo;

  fun<Foo>(foo);
  fun<Baz<Foo>>(foo); // <- this works without the explicit for Baz(T t)

}
```
I'm not sure we implicitly want to allow the last line to work, do we?

**Comment by Yurlungur** [comment]
Ah, I see what you mean. Yes, that's true.

Hmm also I was trying to reproduce the failed code snippet that caused me to raise this issue in the first place, and I can't seem to reproduce at the moment. I will close the issue for now.

**Comment by lroberts36** [comment]
Looking at this a little further, the problem actually appears to be that many calls to `MeshBlockData::PackVariablesAndFluxes(Metadata::FlagCollection &flags,...)` now rely on an implicit conversion from `std::vector<Metadata>` to `Metadata::FlagCollection`. For some reason I don't obviously see, the linter is ok with 
```c++
template <template <class...> class Container_t, class... extra>
FlagCollection(const Container_t<MetadataFlag, extra...> &flags, bool take_union = false) 
``` 
not being marked explicit (if I add an `explicit` I get the same compilation failure), while it is not ok with 
```c++
template<class T, REQUIRES(std::is_same<typename T::value_type, MetadataFlag>::value)>
FlagCollection(const T &flags, bool take_union = false)
``` 
not being marked explicit.

**Comment by lroberts36** [comment]
If I had to guess I would say that cpplint.py isn't set up to parse the more complicated expression `const Container_t<MetadataFlag, extra...> &`

**Comment by Yurlungur** [comment]
Yes... thanks for the reminder. That's what I was encountering @lroberts36. I think I'm beginning to understand:
1. I actually explicitly designed `FlagCollection` to rely on implicit conversions so that downstream code wouldn't need to change.
2. The variatic unpack in the former constructor confuses the linter because it uses that as a heuristic for "this consturctor may have many arguments and is not a single argument constructor."

**Comment by Yurlungur** [comment]
So I guess this speaks to a deeper philosophical issue: Should we allow ourselves to deliberately rely on implicit conversions?

**Comment by lroberts36** [comment]
I would lean towards no, since we have already been enforcing that everywhere and it can lead to some subtle bugs. To get around it in this case, we could do something like 
```c++
template <class... ARGS>
const VariableFluxPack<T> &MeshBlockData::PackVariablesAndFluxes(const std::vector<Metadata> &flags,
                                                    ARGS... &&args) {
    return PackVariablesAndFluxes(FlagCollection(flags), std::forward<ARGS>(args)...);
  }
```

**Comment by Yurlungur** [comment]
Yeah I think that's reasonable. I've renamed the issue and assigned it to me. I will try to find the time to address.

**Comment by lroberts36** [comment]
I am pretty close to it on `jmm/uid-registry`. I will just add it there

**Comment by Yurlungur** [comment]
Sounds good. Thanks. :+1:

**Comment by pgrete** [comment]
+1 on not using/allowing implicit conversion.

**Comment by Yurlungur** [comment]
> I am pretty close to it on `jmm/uid-registry`. I will just add it there

@lroberts36 did you make this change in the `jmm/uid-registry` machinery?

**Comment by lroberts36** [comment]
@Yurlungur: I did make this change there and link this issue to that PR. This should close when it is merged.
