### ISSUE TITLE
Kokkos 4.0.0 / CUDA 12 support?

### ISSUE THREAD

**Issue by BenWibking** [parthenon-hpc-lab/parthenon#842]
Are there any deprecated features or anything else blocking moving to Kokkos 4.0.0?

**Comment by pgrete** [comment]
Not that I am aware of.
I'd be a little cautious with bumping by default at the moment (given that it was just released), but everything should work with a locally updated submodule.
There are even a couple of features that may allow us to cleanup the code base in the long run, see #827

**Comment by Yurlungur** [comment]
I'd like to bump this, as I recently discovered `Kokkos 4+` is required to support our local A100 machine, Chicoma. (Chicoma has a *lot* of problems. There's actually an issue with `Kokkos 4` on Chicoma too that required a manual patch...)
