### ISSUE TITLE
What to do about stable branch?

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#847]
We have not updated the stable branch in quite a while.
Does anyone use/refer to it?

From my point of view we can just delete it as working with tags (for releases) on the dev branch seems to work well (also judging based on the outdated stable branch).

**Comment by Yurlungur** [comment]
I am in favor of deleting the stable branch and relying on tags.

**Comment by pgrete** [comment]
Done as discussed during the sync.
