### ISSUE TITLE
Python formatting does not appear stable

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#856]
Since I've been mucking about in the python recently, I noticed that the local version of black I have, `19.10b0`, does not appear to agree with whatever version the CI is running. We should maybe document the required version somewhere... and possibly upgrade if our CI version is very out of date.

**Comment by pgrete** [comment]
I'm locally running with 
```
$ black --version
black, 22.6.0 (compiled: yes)
Python (CPython) 3.10.10
```
and haven't encountered problems yet.
I also just checked the cpp-format container and it says
```
root@1e487bee17bf:/# black --version
black, 22.3.0 (compiled: yes)
```
So it's not that much out of date (the container was build about a year ago).
Can you easily bump your version?

**Comment by Yurlungur** [comment]
Ah ok so I'm the one out of date. Yes that should be no problem. We should document somewhere what version of black to use, same as we do with clang-format.
