### ISSUE TITLE
Component labels in output

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#864]
Our current machinery to generate component labels (used e.g., in the hdf5/xdmf output and in Ascent) ignores the (base) label when component labels are provided:
https://github.com/parthenon-hpc-lab/parthenon/blob/01cd49ec65506421a1a0b86dd9ae122de68a663d/src/outputs/outputs.cpp#L112

This results in issues (both for Ascent and ParaView) if two vectors use the same labels, say a "density" for a primitive and conserved variable vector (or magnetic fields) as only one component will show up in the analysis tools (all data is written correctly, it's just the use of the component labels).

I see two obvious options:
1. modify the outputs to that they take the base label into account
2. modify the component label creation function to always take the base label into account

I'm in favor of the second as we'd only need to maintain one piece of code and it'd be in line with the case where no labels are provided, i.e., where the base label is used with `_%d` suffix.

Given that this might affect downstream (analysis) codes input from every group would be welcome, ping @Yurlungur @lroberts36 @bprather 
Finally, it'd be great if we could make a decision on a reasonably short timeframe as this will directly the yt frontend.

**Comment by Yurlungur** [comment]
I don't think I use component labels. But I agree with 2. That seems to minimize maintenance burden.

**Comment by c-prather** [comment]
I do not use component labels, and I don't think I will soon enough that I have a strong opinion about the fix here.
