### ISSUE TITLE
Flowchart for tasks

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#880]
At the Athena meeting (and also other discussions) it became clear that having a flow chart of the tasks is very useful.
In principle this should be very straightforward by just writing out our tasks in a given format that is understood by a plotting library, e.g., https://mermaid.js.org/syntax/flowchart.html

While giving it a first shot, I noticed two difficulties
1. I don't fully understand how dependencies work internally (in terms of blocks of bitsets with fixed width and whether a new id [without a task] is created for combined dependencies)
2. there's no straightforward way to get the name of the function we pass to `AddTask`. Even with C++20 `std::source_location` we would only be able to determine where it was called, but not the name itself

Any thoughts/ideas/input, particularly @jdolence @Yurlungur @lroberts36 
Am I missing sth?

One potentially clean option is to add another `AddTask` overload that takes an optional string as (arbitrary) function name, so that downstream codes could decide to make use of it (or not).

**Comment by BenWibking** [comment]
A GraphViz [DOT output](https://graphviz.org/doc/info/lang.html) might also be useful to produce offline SVG and PDF figures.

It would also be useful to have the names of the kernels launched within each task in the graph. Those already have strings, so that might be straightforward(?) for kernels launched via the Parthenon wrapper functions.

**Comment by Yurlungur** [comment]
> I don't fully understand how dependencies work internally (in terms of blocks of bitsets with fixed width and whether a new id [without a task] is created for combined dependencies)

A new task ID is created for combined dependencies. The `|` operator overload returns a new object:

```C++
TaskID TaskID::operator|(const TaskID &rhs) const {
  TaskID res;
  const int n_myblocks = bitblocks.size();
  const int n_srcblocks = rhs.bitblocks.size();
  res.bitblocks.resize(std::max(n_myblocks, n_srcblocks));
  if (n_myblocks == n_srcblocks) {
    for (int i = 0; i < n_myblocks; i++) {
      res.bitblocks[i] = bitblocks[i] | rhs.bitblocks[i];
    }
  } else if (n_myblocks > n_srcblocks) {
    for (int i = 0; i < n_srcblocks; i++) {
      res.bitblocks[i] = bitblocks[i] | rhs.bitblocks[i];
    }
    for (int i = n_srcblocks; i < n_myblocks; i++) {
      res.bitblocks[i] = bitblocks[i];
    }
  } else {
    for (int i = 0; i < n_myblocks; i++) {
      res.bitblocks[i] = bitblocks[i] | rhs.bitblocks[i];
    }
    for (int i = n_myblocks; i < n_srcblocks; i++) {
      res.bitblocks[i] = rhs.bitblocks[i];
    }
  }
  return res;
}
```

> there's no straightforward way to get the name of the function we pass to AddTask. 

Hmm. I agree with @benwibking that one could use Kokkos profiling regions perhaps. I'd be in favor of the string naming machinery. We could also make a macro that wraps it

```C++
#define ADD_TASK(tl, dep, func, ...) tl.AddTask(#func, dep, func, __VA_ARGS__);
```
where here `tl.AddTask(std::string, TaskId, F, Args...)` is assumed to exist.

**Comment by Yurlungur** [comment]
Actually without care the macro approach might be tough, since it probably can't handle templated function names if they have commas in them.
