### ISSUE TITLE
Default host OpenMP?

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#897]
Currently, we enable OpenMP (threading) by default in Parthenon.
In AthenaPK (and most machine files), we disable it by default as we never really saw a good speedup versus flat MPI.

Any objection to change the default to (`serial` on the host)?
This would also allow to remove the `PARTHENON_DISABLE_OPENMP` parameter (and associated logic) and we could just rely on `Kokkos_ENABLE_OPENMP`.

ping @Yurlungur @jdolence @lroberts36 @brryan @bprather

**Comment by Yurlungur** [comment]
So long as it is still possible to enable openmp kokkos backend this is fine for me. There's interest at LANL in using openmp, but I think having sensible defaults for optimal performance makes sense.

**Comment by lroberts36** [comment]
Yeah, I think this sounds good. I also have never seen particularly good OpenMP performance, so having serial by default seems better.

**Comment by c-prather** [comment]
Very much in favor of this, and not for any speed-related reasons.

I just last week hit an issue where OpenMP had to be disabled (the Cray compiler wrapper on Frontier assumes OpenMP == OpenMP target).  Having to disable it at each of the KHARMA, Parthenon, and Kokkos levels was a mess, so I'm happy having less logic around this in general.

The user knows whether they need OpenMP and already has Kokkos_ENABLE_OPENMP to say so, we should respect it.

**Comment by pgrete** [comment]
Thanks for the quick feedback.
I made the changes in #896
