### ISSUE TITLE
`std::array` access on device

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#898]
At various places (mostly `dims_` etc) are `std::array` that are accessed through `[]` in device code.
That may (or may not work) and we should probably use `Kokkos::Array`.

**Comment by BenWibking** [comment]
This has always worked for me. Is there a specific set of circumstances where this doesn't work?

**Comment by BenWibking** [comment]
This suggests that it should work for CUDA when `--expt-relaxed-constexpr` is used and `-std=c++17` is on: https://github.com/NVIDIA/libcudacxx/issues/51

**Comment by pgrete** [comment]
Interesting, I might need to revisit the compiler warnings I got. Closing for now.
